### ISSUE TITLE
[Question] it seems timeout exception beacause of browser cant be instance 

### ISSUE THREAD

**Issue by 1355692540** [microsoft/playwright-java#1018]
the code run well when in idea .but when l make as an jar and use java -jar.  alaways tell me timeout excepltion. 

```
Exception in thread "main" com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\server\progress.js:96:26)
    at Chromium.launch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\server\browserType.js:79:38)
    at BrowserTypeDispatcher.launch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\dispatchers\browserTypeDispatcher.js:57:40)
    at DispatcherConnection.dispatch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\dispatchers\dispatcher.js:352:46)
}
        at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
        at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:49)
        at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:41)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
        at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:41)
        at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:32)
        at Cc.<init>(Cc.java:358)
        at Aa.main(Aa.java:65)
Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\server\progress.js:96:26)
    at Chromium.launch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\server\browserType.js:79:38)
    at BrowserTypeDispatcher.launch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\dispatchers\browserTypeDispatcher.js:57:40)
    at DispatcherConnection.dispatch (C:\Users\86156\AppData\Local\Temp\playwright-java-870233131096163806\package\lib\dispatchers\dispatcher.js:352:46)
}
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:181)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:163)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
        ... 10 more
```

**Comment by yury-s** [comment]
Which browser is that?

Can you share the code please and command line that you use to launch it? You may have missed the driver package. Also running with DEBUG=pw:browser may give you some information on what the browser is doing during the startup.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
