### ISSUE TITLE
[BUG] java.lang.RuntimeException: Failed to create driver when trying to start Playwright in Minecraft Plugin

### ISSUE THREAD

**Issue by mrmrmystery** [microsoft/playwright-java#1043]
**Context:**
- Playwright Version: 1.17.0
- Operating System: Linux, Windows (Both same error)
- Browser: Firefox
- Extra: Running inside a Minecraft 1.19.2 Plugin

Error
```
java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at com.microsoft.playwright.Playwright.create(Playwright.java:92) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at com.microsoft.playwright.Playwright.create(Playwright.java:96) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at de.somewhatcity.traincartsplus.maps.Renderer.init(Renderer.java:35) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at de.somewhatcity.traincartsplus.Traincartsplus.onEnable(Traincartsplus.java:44) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1747]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
        at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:78) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:38) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) ~[traincartsplus-1.0-SNAPSHOT.jar:?]
        ... 16 more
```

Playwright won't start packaged inside a minecraft plugin because it fails to create drivers.

**Comment by yury-s** [comment]
Since this is a custom build, you need to ensure yourself that `DriverJar` inside `traincartsplus-1.0-SNAPSHOT.jar` can actually access the driver resources to extract them or supply your own `Driver` implementation. We cannot provide more specific advise since we don't know much about how playwright is packaged/run in the app. If we can help you by extending our API please let us know.
