### ISSUE TITLE
[Question] page.waitForRequest() timing out even after completing the specified action

### ISSUE THREAD

**Issue by pranesh517** [microsoft/playwright-java#1065]
**Code:**

```java
Page page = browserContext.newPage();
        page.navigate("https://rahulshettyacademy.com/AutomationPractice/");

        page.waitForRequest(request -> "https://www.rahulshettyacademy.com/api/course".equals(request.url()) && "GET".equals(request.method()), () ->{
            page.click("#alertbtn");
        });
 browserContext.close();
 browser.close();
 playwright.close();
```
------------------------------------------------------------------------------------------------------------------------------
Here Alert button is getting clicked, i also tried with any other action like entering value in text field. Those actions are being performed but i am getting below error:
```
Exception in thread "main" com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded
	at com.microsoft.playwright.impl.WaitableTimeout.get(WaitableTimeout.java:41)
	at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:44)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.PageImpl.waitForEventWithTimeout(PageImpl.java:534)
	at com.microsoft.playwright.impl.PageImpl.waitForRequestImpl(PageImpl.java:1362)
	at com.microsoft.playwright.impl.PageImpl.lambda$waitForRequest$73(PageImpl.java:1351)
	at com.microsoft.playwright.impl.WaitForEventLogger.get(WaitForEventLogger.java:46)
	at com.microsoft.playwright.impl.ChannelOwner.withWaitLogging(ChannelOwner.java:78)
	at com.microsoft.playwright.impl.PageImpl.waitForRequest(PageImpl.java:1351)
	at com.microsoft.playwright.Page.waitForRequest(Page.java:6456)
	at Sample14.main(Sample14.java:13)
```
browser is still open and close() was not called.

**Comment by yury-s** [comment]
The request you are waiting for is actually sent before the click. You can record [a trace](https://playwright.dev/java/docs/trace-viewer-intro) to see what's going on in the page. Or you can just add the following logging to your code to see all requests that are sent while `page.waitForRequest` is being called:

```java
    page.onRequest(r -> System.out.println(r.url()));
    page.waitForRequest(request -> "https://www.rahulshettyacademy.com/api/course".equals(request.url()) && "GET".equals(request.method()), () ->{
            page.click("#alertbtn");
    });
```

Rearranging the code like this will pass the test (not sure if that's what you want though):

```java
    page.onRequest(r -> System.out.println(r.url()));
    page.waitForRequest(request -> "https://www.rahulshettyacademy.com/api/course".equals(request.url()) && "GET".equals(request.method()), () ->{
      page.navigate("https://rahulshettyacademy.com/AutomationPractice/");
      page.click("#alertbtn");
    });
```

**Comment by pranesh517** [comment]
I interpreted working of page.waitForRequest() little different. It worked now, this was expected and i understood its intent as well. Thank you for quick turn around.
