### ISSUE TITLE
[Feature] printdeps.exe executable blocked - Unable to open traces

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright-java#1089]
Hi guys,

we have the following issue, company policy is strics and we are unable to open the traces zip file via web -> [trace.playwright.dev]

So I was trying to open the traces using Playwright CLI, unfortunatelly I am getting a pop up that due to security policy the printdeps.exe is blocked.

![image](https://user-images.githubusercontent.com/94455079/194301453-691cc16b-7222-4ed6-b2c9-a429633d1b2b.png)

I had similar problem with nodejs, but this was sorted out by using PLAYWRIGHT_NODEJS_PATH.

But what about the printdeps, is there a similar solution with env variable?

**Comment by yury-s** [comment]
> But what about the printdeps, is there a similar solution with env variable?

Unfortunately no, this is a part of playwright, we build this executable ourselves and ship it along with each playwright release, unlike Node.js there is no alternative place to install it from. You'll need to add an exception for that binary to the security policy. It will likely require the binary to be signed, which is another issue tracked in https://github.com/microsoft/playwright/issues/17165 (please upvote that issue if the binary is required to be signed in order to work in your environment).

**Comment by mEklavya** [comment]
@NikkTod How did you use PLAYWRIGHT_NODEJS_PATH? I have tried to use it, it is solving the issue of the node.exe policy exception but getting the below error.
Files\nodejs\x was unexpected at this time.
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:164)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:108)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:78)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:141)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:52)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.microsoft.playwright.Playwright.create(Playwright.java:100)

**Comment by NikkTod** [comment]
Hey @mEklavya, I just added it with env variable and it worked.

![image](https://user-images.githubusercontent.com/94455079/213224149-51aadb5c-01be-4c64-ba86-c39b069cb5e0.png)
