### ISSUE TITLE
[BUG] Failed to read message from driver, pipe closed.

### ISSUE THREAD

**Issue by NICOGTZL** [microsoft/playwright-java#1117]
**Context:**
- Playwright Version: [what Playwright version do you use?]
1.27.0
- Operating System: [e.g. Windows, Linux or Mac]
Windows 10
- Browser: [e.g. All, Chromium, Firefox, WebKit]
Chromium
- Extra: [any specific details about your environment]
Gradle

**Error**
```
<--- Last few GCs --->

[9632:000001B06C846820] 19031491 ms: Mark-sweep 4041.7 (4144.2) -> 4040.3 (4143.8) MB, 816.9 / 0.0 ms  (average mu = 0.618, current mu = 0.005) allocation failure scavenge might not succeed
[9632:000001B06C846820] 19033475 ms: Mark-sweep 4040.7 (4144.0) -> 4040.7 (4144.3) MB, 1982.6 / 0.0 ms  (average mu = 0.358, current mu = 0.000) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6A707B34F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+123599
 2: 00007FF6A7008CB6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65206
 3: 00007FF6A7009D8D node::OnFatalError+301
 4: 00007FF6A793C36E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6A792694D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF6A77C9F2C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF6A77C7044 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF6A77C49C0 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF6A77E26D0 v8::internal::FreeListManyCached::Reset+1408
10: 00007FF6A77E2D85 v8::internal::Factory::AllocateRaw+37
11: 00007FF6A77F845B v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString+75
12: 00007FF6A75DBC9B v8::internal::String::SlowFlatten+395
13: 00007FF6A73467BB v8::internal::WasmTableObject::Fill+603
14: 00007FF6A7946126 v8::String::Utf8Length+22
15: 00007FF6A6F24423 v8::internal::compiler::Reducer::NoChange+35715
16: 00007FF6A6F28966 v8::internal::LookupIterator::array_index+9926
17: 00007FF6A6F281DF v8::internal::LookupIterator::array_index+7999
18: 00007FF6A78F6D46 v8::internal::Builtins::code_handle+172806
19: 00007FF6A78F6939 v8::internal::Builtins::code_handle+171769
20: 00007FF6A78F6BFC v8::internal::Builtins::code_handle+172476
21: 00007FF6A78F6A60 v8::internal::Builtins::code_handle+172064
22: 00007FF6A79CA141 v8::internal::SetupIsolateDelegate::SetupHeap+494641
23: 000001B06CBA9844 
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:169)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:113)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.FrameImpl.isVisibleImpl(FrameImpl.java:640)
	at com.microsoft.playwright.impl.FrameImpl.lambda$isVisible$30(FrameImpl.java:626)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.FrameImpl.isVisible(FrameImpl.java:626)
	at com.microsoft.playwright.impl.LocatorImpl.isVisible(LocatorImpl.java:339)
	at com.microsoft.playwright.Locator.isVisible(Locator.java:2759)
	at com.nicogtzl.tracker.warehouse.stock.stock_creator.checkListing(stock_creator.java:78)
	at com.nicogtzl.tracker.warehouse.stock.stock_creator.gettingInfoToCreateG2GListing(stock_creator.java:50)
	at com.nicogtzl.tracker.warehouse.warehouse_controller.warehouse_control(warehouse_controller.java:20)
	at com.nicogtzl.tracker.Main.main(Main.java:29)
Caused by: java.io.EOFException
	at com.microsoft.playwright.impl.ReaderThread.readIntLE(PipeTransport.java:110)
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:139)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:125)
Caused by: java.io.EOFException


> Task :Main.main() FAILED

Execution failed for task ':Main.main()'.
> Process 'command 'C:/jdk-18.0.2.1/bin/java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.



```

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
private static void checkListing(String ID) throws InterruptedException, IOException {
        Page page1 = bx1.newPage();

        String url = amazon + ID;

        checkingConnection(); //just to check we do have internet
        if (!page1.url().equals(url)) {
            try {
                page1.navigate(url);
            } catch (Exception e) {
                System.out.println(e.getMessage());
                System.out.println(alert + "[10] Could not load the marketplace, retrying in 15 seconds...");
                page1.close();
                TimeUnit.SECONDS.sleep(15);
                gettingInfoToCreateG2GListing();
            }
        }

        try {
            if (page1.locator(".search-result__text").isVisible()) {
                int result = Integer.parseInt(page1.locator(".search-result__text").textContent().replaceAll("[^0-9]", ""));
                if (result <= 0) {
                    adCreated = false;
                    System.out.println("The ad is unavailable.");
                } else if (result > 1) {
                    System.out.println("Ad is available.");
                    trackPrice(ID);
                } else {
                    adCreated = true;
                    System.out.println("Ad is created but unavailable");
                }
            }
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
            System.out.println(alert + "[11] Could not load the marketplace, retrying in 15 seconds...");
            page1.close();
            TimeUnit.SECONDS.sleep(15);
            checkListing(ID);
        }
        page1.close();
    }
```

**Describe the bug**
I just woke up and found this error, not sure how to fix it.

Add any other details about the problem here.

**Comment by yury-s** [comment]
As the error says Node.js ran out of memory. Have you been running it for a long time with many URLs reusing the same BrowserContext? (I assume bx1 is a BrowserContext). You should close the context after test is done and create another one for better isolation and to let playwright properly release all resources associated with the context (not all of them are cleaned-up when just the page is closing).

**Comment by NICOGTZL** [comment]
> As the error says Node.js ran out of memory. Have you been running it for a long time with many URLs reusing the same BrowserContext? (I assume bx1 is a BrowserContext). You should close the context after test is done and create another one for better isolation and to let playwright properly release all resources associated with the context (not all of them are cleaned-up when just the page is closing).

Yes that is what I was doing, so I do have to close the context after I finish? Cannot I reuse it without closing it? The problem is that I have to login everytime a context browser opens, I'm not sure if can I automatize the Google Authenticator.

**Comment by yury-s** [comment]
> Cannot I reuse it without closing it?

You can but some of the resources will be held alive in memory until the context is disposed (such as old network requests). 

> The problem is that I have to login everytime a context browser opens, I'm not sure if I can automatize the Google Authenticator.

You can export the authenticated state somewhere using [BrowserContext.storageState](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-storage-state)  and later pass it as an argument to [Browser.newContext](https://playwright.dev/java/docs/api/class-browser#browser-new-context-option-storage-state). This will restore cookies and localStorage state.
