### ISSUE TITLE
[BUG] failed to create driver when running from a jar artifact

### ISSUE THREAD

**Issue by AriaMoradi** [microsoft/playwright-java#1138]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Arch Linux
- Browser: Chrominum
- Extra: -

## System:
 - OS: Linux 6.0 Arch Linux
 - Memory: 7.30 GB / 15.48 GB
 - Container: Yes
## Binaries:
 - Node: 14.21.0 - /usr/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.19.2 - /usr/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

My code runs fine when running using gradle run. The issue happens when I build an uber jar using `shadowJar` and run the app from the jar file. 

The code is available at https://github.com/Suwayomi/Tachidesk-Server/blob/f47dc6b9dea927e55179186d07afac1ad9927be4/server/src/main/kotlin/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt

Here's the stack trace:

```
java.io.IOException: java.lang.RuntimeException: Failed to create driver
	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:52)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:19)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:32)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at rx.Subscriber.setProducer(Subscriber.java:205)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:54)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10423)
	at rx.Observable.subscribe(Observable.java:10390)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:29)
	at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:24)
	at suwayomi.tachidesk.manga.impl.MangaList.getMangaList(MangaList.kt:35)
	at suwayomi.tachidesk.manga.controller.SourceController$popular$2$1.invokeSuspend(SourceController.kt:78)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.microsoft.playwright.Playwright.create(Playwright.java:100)
	at eu.kanade.tachiyomi.network.interceptor.CFClearance.resolveWithWebView(CloudflareInterceptor.kt:76)
	at eu.kanade.tachiyomi.network.interceptor.CloudflareInterceptor.intercept(CloudflareInterceptor.kt:46)
	... 34 common frames omitted
Caused by: java.nio.file.FileSystemAlreadyExistsException: null
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:104)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.extractDriverToTempDir(DriverJar.java:116)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:66)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
	... 41 common frames omitted
```

Seems like `Driver.createAndInstall` is calling `DriverJar.initialize` and which calls `extractDriverToTempDir` and it's trying to read from `driver/` in resources which wasn't bundled in my uber jar file. however I could find some files inside the `driver` dir directly inside the jar.

You can download a build artifact from here: https://github.com/Suwayomi/Tachidesk-Server-preview/releases/download/v0.6.6-r1165/Tachidesk-Server-v0.6.6-r1165.jar

Also this issue seems to be related to #1043 but I couldn't find anything about packaging PlayWright anywhere?

**Comment by Syer10** [comment]
Happens to me on Windows as well

**Comment by Syer10** [comment]
The drivers are included in the dependencies like so and it doesn't work
```
    implementation("com.microsoft.playwright:playwright:1.28.0")
    implementation("com.microsoft.playwright:driver-bundle:1.28.0")
    implementation("com.microsoft.playwright:driver:1.28.0")
```
Is there an issue with Playwright-java and fatjars?

**Comment by Syer10** [comment]
I just checked and it looks like the fatjar includes all the driver files correctly
![H4zacB4 1](https://user-images.githubusercontent.com/6090655/205794124-a4c8a55e-88c0-43d0-b688-a3742090f00e.png)
