### ISSUE TITLE
[BUG] jar not work

### ISSUE THREAD

**Issue by cosoc** [microsoft/playwright-java#1152]
**Context:**

```
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105) ~[driver-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57) ~[driver-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45) ~[playwright-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35) ~[playwright-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) ~[playwright-1.28.1.jar!/:1.28.1]
	at cn.cosoc.snailx.module.ResourceManagerCore.lambda$resourceDownloadDoFunction$0(ResourceManagerCore.java:95) ~[classes!/:2.0.0]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:359) ~[na:na]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288) ~[na:na]
	at com.microsoft.playwright.impl.driver.jar.DriverJar.maybeExtractNestedJar(DriverJar.java:160) ~[driver-bundle-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.driver.jar.DriverJar.extractDriverToTempDir(DriverJar.java:113) ~[driver-bundle-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:66) ~[driver-bundle-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64) ~[driver-1.28.1.jar!/:1.28.1]
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101) ~[driver-1.28.1.jar!/:1.28.1]
	... 6 common frames omitted

```

**Code Snippet**

**Describe the bug**

Why can't the program run after the jar is packaged!

**Comment by yury-s** [comment]
It depends on how you package the driver and whether the default loader can find it. Can you share more details about your setup and how you deploy your application that uses playwright? If you use custom bundler you may be better off configuring custom [driver loader](https://github.com/microsoft/playwright-java/blob/4246c375ac1e9cec4f75c14592e5ab041e3f65b6/driver/src/main/java/com/microsoft/playwright/impl/driver/Driver.java#L115-L116) class.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
