### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object

### ISSUE THREAD

**Issue by shilpashilpamona** [microsoft/playwright-java#1156]
Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object

**Comment by shilpashilpamona** [comment]
Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
ProtocolError: Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
    at D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:230:24
    at new Promise (<anonymous>)
    at CDPSession.send (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:226:16)
    at ExecutionContext._evaluateInternal (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at ElementHandle.evaluateHandle (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:125:46)
    at Object.internalHandler.queryOne (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\QueryHandler.js:24:44)
    at ElementHandle.$ (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:781:29)
    at DOMWorld.$ (D:\nodescript\node_modules\puppeteer-core\lib\cjs\puppeteer\common\DOMWorld.js:101:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
