### ISSUE TITLE
[BUG] [Java] Cannot find object to call __adopt__" error appears after updating playwright 1.17 to 1.28 

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [microsoft/playwright-java#1184]
**Context:**
- Playwright Version: 1.28.0 and 1.29.0
- Operating System: Linux
- Browser: Chromium
- Extra: Playwright for java
- Java 11
- Tests executed in parallel mode (10-20 threads)
- 60% of tests area failed due to this bug (28 of 45 tests)

**Describe the bug**

```
com.microsoft.playwright.PlaywrightException: Cannot find object to call __adopt__: page@dc44a43c7246ce63f53bcffd98c83d8e
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:218)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.FrameImpl.waitForSelectorImpl(FrameImpl.java:1064)
	at com.microsoft.playwright.impl.LocatorImpl.lambda$waitForImpl$7(LocatorImpl.java:555)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LocatorImpl.waitForImpl(LocatorImpl.java:555)
	at com.microsoft.playwright.impl.LocatorImpl.waitFor(LocatorImpl.java:551)
	at com.tradeix.stepdefs.ui.pages.CommonPage.waitPageLoaded(CommonPage.kt:76)
```
```
com.microsoft.playwright.PlaywrightException: Cannot find object to call __adopt__: page@cc95979e5f4752982d4ce66eafc3a1eb
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:218)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:98)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPageImpl(BrowserContextImpl.java:355)
	at com.microsoft.playwright.impl.BrowserContextImpl.lambda$newPage$12(BrowserContextImpl.java:348)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:348)
	at com.microsoft.playwright.impl.BrowserContextImpl.newPage(BrowserContextImpl.java:43)
```

as you can see this error raised in different parts of code
[playwright_example.zip](https://github.com/microsoft/playwright/files/10480014/playwright_example.zip)

Gradle project to reproduce the problem, just run `gradlew test`

**Comment by yury-s** [comment]
The problem is that you run all tests in parallel with the same instance of playwright. You should create one instance of Playwright per thread to avoid multithreading problems like this, see [this document](https://playwright.dev/java/docs/multithreading). Something like this should do:

```kt

class TestPlaywright {
    val playwright: Playwright
    val browser: Browser

    constructor() {
        playwright = create()
        browser = playwright.chromium().launch()
        System.out.println("New browwser" + Thread.currentThread().id)
    }
```

**Comment by CrazedCoderNate** [comment]
Just ran into this issue. I can confirm I was also using the same instance of playwright across multiple threads. Thanks yury!

**Comment by yury-s** [comment]
We considered having a guard against playwright being used from multiple threads (which would throw if an instance is used from 2 different threads). Maybe it's worth implementing.

**Comment by wissamsu** [comment]
Just ran into the same problem and was wondering wouldnt it be too much to create a new playwright for each user.
