### ISSUE TITLE
[BUG] "Object doesn't exist" exception on Page close with onRequestFinished listener

### ISSUE THREAD

**Issue by rkennedy-mode** [microsoft/playwright-java#1197]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Linux
- Browser: Chromium
- Extra: AWS ECS Fargate-based service

**Code Snippet**

We have a piece of code that we use to instrument Playwright activity using OpenTelemetry. One piece in particular hooks the `onRequestFinished` callback:

```java
public class PlaywrightInstrumenter {
    public static void instrumentPage(Page page) {
        Map<Request, Span> activeRequests = new HashMap<>();
        browserContext.onRequestFinished(request -> {
            Optional.ofNullable(activeRequests.remove(request)).ifPresent(span -> {
                span.setAttribute("responseStatus", request.response().status());
                span.setAttribute("responseStatusText", request.response().statusText());
                span.end();
            });
        });
    }
}
```

Elsewhere, we have code that creates the page in a try-with-resources block:

```java
try (BrowserContext browserContext = TRACER.call("create-context", () -> browser.newContext(browserOptions));
     TracingContext tracingContext = startTracing(browserContext, captureInfo);
     Page page = TRACER.call("create-page", browserContext::newPage)) {
    PlaywrightInstrumenter.instrument(page);
    nagivate(page);
    screenshot(page);
}
```

**Describe the bug**

When the Page object is auto-closed via try-with-resources, we often (but not always) see the following exception:

```
Caused by: com.microsoft.playwright.PlaywrightException: Object doesn't exist: page@09c660782a8b2a8a414a95043e4bafc0
        at com.microsoft.playwright.impl.Connection.getExistingObject(Connection.java:162)
        at com.microsoft.playwright.impl.BrowserContextImpl.handleEvent(BrowserContextImpl.java:604)
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:233)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:98)
        at com.microsoft.playwright.impl.RequestImpl.lambda$response$3(RequestImpl.java:150)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
        at com.microsoft.playwright.impl.RequestImpl.response(RequestImpl.java:149)
        at com.microsoft.playwright.impl.RequestImpl.response(RequestImpl.java:36)
        at com.modeanalytics.cappie.instrumentation.PlaywrightInstrumenter.lambda$instrumentBrowserContext$3(PlaywrightInstrumenter.java:51)
        at java.util.Optional.ifPresent(Optional.java:159)
        at com.modeanalytics.cappie.instrumentation.PlaywrightInstrumenter.lambda$instrumentBrowserContext$4(PlaywrightInstrumenter.java:50)
        at com.microsoft.playwright.impl.ListenerCollection.notify(ListenerCollection.java:44)
        at com.microsoft.playwright.impl.BrowserContextImpl.handleEvent(BrowserContextImpl.java:602)
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:233)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
        at com.microsoft.playwright.impl.PageImpl.close(PageImpl.java:517)
        at com.microsoft.playwright.Page.close(Page.java:3667)
```

The problem appears to be that when the `onRequestFinished` callback is invoked, the method handler may encounter this PlaywrightException via some error deep in Playwright when requesting the `Response` object via a call to `response()` (in order to retrieve the response status code). The exception seems to indicate that it can't find the `Page` object, which could make sense given this is all happening in the context of `Page.close()`. My best guess is that the reference is being cleared prior to the callbacks being fired, despite the callbacks depending on that reference.

**Comment by yury-s** [comment]
Can you share a minimal example which we could run locally? I tried with the following code and was not able to reproduce it:

```java
    try (Browser browser1 = browserType.launch()) {
      try (BrowserContext context1 = browser1.newContext()) {
        Page page1 = context1.newPage();
        page1.onRequestFinished(r -> {
          System.out.println(r.url() + ": " + r.response().status());
          System.out.println("   " + r.response().statusText());
        });
        page1.navigate(server.PREFIX + "/frames/two-frames.html", new Page.NavigateOptions().setWaitUntil(WaitUntilState.COMMIT));
        System.out.println("will close");
        page1.close();
        System.out.println("did close");
      }
    }
    System.out.println("done");
```
Also, can you run with `DEBUG=pw:channel` and post the log here?

**Comment by rkennedy-mode** [comment]
As mentioned above, this doesn't reliably occur. We have code running in our production environment where I can observe this happening via our telemetry and logs.

> Also, can you run with DEBUG=pw:channel and post the log here?

Yes, although probably not for a few days as I'm busy with some other tasks.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
