### ISSUE TITLE
Java Playwright - Cannot run program ... playwright.sh

### ISSUE THREAD

**Issue by mwduncan2018** [microsoft/playwright-java#1210]
The following error occurs when I run a basic Java Playwright test for the first time. The organization requires that Centos is used. I'm using Maven. Has anyone experienced this error before and how did you resolve it? Thank you.

Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-17246735617012366256/playwright.sh": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:45)
	... 27 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 29 more

**Comment by yury-s** [comment]
You can try pause inside `DriverJar.installBrowsers` when the driver is already extracted in a temp dir but before playwright.sh is executed  and check its permissions. The error unambiguously points to a problem with the file permissions. Which playwright version are you using? Do you load it via maven deps or build manually?

**Comment by mwduncan2018** [comment]
Hi yury-s.
Thank you for assisting. My team has decided to use Python Playwright instead, which is not having this problem when executing. I was able to execute Java Playwright on Ubuntu with no issues, but I must use Centos on the job. Again, thank you.

**Comment by msangel** [comment]
Is there an official workaround for cases when /tmp is `noexec` ? Like a custom installation directory? 
I am using `playwright/java:v1.27.0-focal` as a base.....

**Comment by vivekgoel15** [comment]
I am still facing it with playwright 1.30.0 using Java. We have read/write/execute permissions for /tmp folder through Jenkins user but as the child folder playwright-java-17246735617012366256 and script playwright.sh is created and removed dynamically so not sure about the permission on those. Can someone please take a look?
