### ISSUE TITLE
Not able to use system node JS path  - C:\Program is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mEklavya** [microsoft/playwright-java#1213]
- Playwright Version:1.30.0
- Operating System: Windows
- Browser: Tried for Chrome

Java

try (Playwright playwright = Playwright.create()) {
			Browser browser = playwright.chromium().launch(
		    		  new BrowserType.LaunchOptions().setHeadless(false)
		    		  .setExecutablePath(Paths.get("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"))
		    		  );
		     
		      Page page1 = browser.newPage();
		      page1.navigate("http://playwright.dev");
		      System.out.println(page1.title());
}
Setting up the NODE JS PATH with the below env property
PLAYWRIGHT_NODEJS_PATH=C:\Program Files\nodejs
Also used below property
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

Code works fine if use existing nodeJS, if we set PLAYWRIGHT_NODEJS_PATH then we are getting below error
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:175)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:79)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:152)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:52)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)

Add any other details about the problem here.
![image](https://user-images.githubusercontent.com/42370888/220539223-625f0553-b655-45ad-bd47-b1436f4c2af5.png)

**Comment by mxschmitt** [comment]
`PLAYWRIGHT_NODEJS_PATH` needs to point to `node.exe` and not the folder. Can you confirm you do that?

**Comment by mEklavya** [comment]
> `PLAYWRIGHT_NODEJS_PATH` needs to point to `node.exe` and not the folder. Can you confirm you do that?

Yes tried both ways with C:\Program Files\nodejs\node.exe also without  node.exe, the error remains the same.

**Comment by mEklavya** [comment]
> > `PLAYWRIGHT_NODEJS_PATH` needs to point to `node.exe` and not the folder. Can you confirm you do that?
> 
> Yes tried both ways with C:\Program Files\nodejs\node.exe also without node.exe, the error remains the same.

Please note that if we put the system node on another path that does not have space it works fine. I feel it is an issue of spaces in the path, can you please check

**Comment by NikkTod** [comment]
Having the same problem, it seems that the space in the path "C:\Program Files" is now causing problems. 

@mEklavya thanks for giving the tip to use double quotes in env property.
