### ISSUE TITLE
[BUG] Page.waitForPopup timeouts with Chrome extension launched new tab

### ISSUE THREAD

**Issue by easyrepro** [microsoft/playwright-java#1215]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Browser: Chromium

**Code Snippet:**

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
        BrowserType type = playwright .chromium();
        BrowserType.LaunchPersistentContextOptions launchPersistentContextOptions = new BrowserType.LaunchPersistentContextOptions();
        launchPersistentContextOptions = launchPersistentContextOptions.setHeadless(false);
        String extPath = "//path/to/extension";
        launchPersistentContextOptions.setArgs(Arrays.asList("--use-fake-ui-for-media-stream","--load-extension="+extPath,"--disable-extensions-except="+extPath));
        BrowserContext context = type.launchPersistentContext(Paths.get(""), launchPersistentContextOptions);
        Page page = context.pages().get(0);
        page.navigate("http://gmail.com");
        page.bringToFront();
        Page page1 = page.waitForPopup( new Page.WaitForPopupOptions().setTimeout(60000) ,()->{
            page.frameLocator("css=#__sideFrame").locator("css=[data-testid='modal'] button").click();
        });
        page1.url();
    }
  }
}
```

**Error**
```java
com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded
	at com.microsoft.playwright.impl.WaitableTimeout.get(WaitableTimeout.java:41)
	at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:44)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at com.microsoft.playwright.impl.PageImpl.waitForEventWithTimeout(PageImpl.java:508)
	at com.microsoft.playwright.impl.PageImpl.waitForPopupImpl(PageImpl.java:476)
	at com.microsoft.playwright.impl.PageImpl.lambda$waitForPopup$4(PageImpl.java:469)
	at com.microsoft.playwright.impl.WaitForEventLogger.lambda$get$0(WaitForEventLogger.java:50)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.WaitForEventLogger.get(WaitForEventLogger.java:41)
	at com.microsoft.playwright.impl.ChannelOwner.withWaitLogging(ChannelOwner.java:80)
	at com.microsoft.playwright.impl.PageImpl.waitForPopup(PageImpl.java:469)
```

**Describe the bug**

While launching chrome browser, loading a chrome extension. After the page is loaded, clicking on a button from extension page (which is loaded inside a frame). This opens a new tab.
page.waitForPopup is always timing out and could not get new page object.

**Comment by easyrepro** [comment]
**Update**: If I replace `page.waitForPopup` with `context.waitForPage` timeout is not happening

Is this expected?

Also it will be helpful to document when to use `context.waitForPage` vs `page.waitForPopup`

**Comment by yury-s** [comment]
If the page is opened by the extension it may well not be caught by `waitForPopup` (perhaps the extension doesn't preserve the link between the new page and the original page where the click occurred). waitForPopup is only guaranteed to catch popups opened via web APIs (window.open, link click etc). If `context.waitForPage` works for you I suggest you proceed with it to avoid possible issues.
