### ISSUE TITLE
[BUG] GraalVM ClassNotFoundException: com.microsoft.playwright.impl.driver.jar.DriverJar

### ISSUE THREAD

**Issue by Ziedelth** [microsoft/playwright-java#1235]
### System info
- Playwright Version: [v1.31.0]
- Operating System: [Windows 11, Ubuntu 20]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

**MainKt**
```kotlin
import com.microsoft.playwright.Page
import com.microsoft.playwright.Playwright
import java.io.File

fun main() {
    val playwright = Playwright.create()
    val browser = playwright.chromium().launch()
    val page = browser.newPage()

    page.navigate("https://www.google.com")
    page.screenshot(Page.ScreenshotOptions().setPath(File("screenshot.png").toPath()))

    browser.close()
    playwright.close()
}
```
**pom.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>example_playwright</artifactId>
    <groupId>org.example</groupId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>consoleApp</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
    </properties>

    <repositories>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.20</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <imageName>${project.artifactId}</imageName>
                            <mainClass>MainKt</mainClass>
                            <buildArgs>
                                <arg>--enable-https</arg>
                                <arg>--no-fallback</arg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.8.0</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass>MainKt</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>7</source>
                    <target>7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.31.0</version>
        </dependency>
    </dependencies>
</project>
```

**Dockerfile**
```dockerfile
FROM maven:3.8.4-openjdk-11-slim AS build

FROM ghcr.io/graalvm/native-image:22.3.1
COPY --from=build /usr/share/maven /opt/maven

ENV M2_HOME=/opt/maven
ENV MAVEN_HOME=/opt/maven
ENV PATH=${M2_HOME}/bin:${PATH}

ENTRYPOINT ["mvn", "clean", "-Pnative", "package"]
```

**Steps**
- docker build -t builder .
- docker run --mount type=bind,source="$(pwd)",target=/app builder
- docker run --mount type=bind,source="$(pwd)",target=/app -it ubuntu bash 
- cd /app/target && ./example_playwright

**Expected**

The binary compiled by GraalVM is supposed to run without error and to make a screenshot of the given page.

**Actual**

An error occurred at launch :

```
Exception in thread "main" java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
        at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
        at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
        at com.microsoft.playwright.Playwright.create(Playwright.java:110)
        at com.microsoft.playwright.Playwright.create(Playwright.java:114)
        at MainKt.main(Main.kt:6)
        at MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: com.microsoft.playwright.impl.driver.jar.DriverJar
        at java.base@17.0.6/java.lang.Class.forName(DynamicHub.java:1132)
        at java.base@17.0.6/java.lang.Class.forName(DynamicHub.java:1105)
        at com.microsoft.playwright.impl.driver.Driver.newInstance(Driver.java:117)
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:99)
        ... 7 more
```

**Comment by yury-s** [comment]
By default GraalVM doesn't package resources properly in the native image, you need to provide some extra configuration. See [this comment](https://github.com/microsoft/playwright-java/issues/403#issuecomment-1123126062) for more details. Folding this issue into https://github.com/microsoft/playwright-java/issues/403

**Comment by Ziedelth** [comment]
I changed the configuration, but the error still appears

**MainKt**
```kotlin
import com.microsoft.playwright.Page
import com.microsoft.playwright.Playwright
import java.io.File
import java.net.URI
import java.nio.file.FileSystems

fun main() {
    FileSystems.newFileSystem(URI("resource:/"), mapOf("create" to "true"))

    val playwright = Playwright.create()
    val browser = playwright.chromium().launch()
    val page = browser.newPage()

    page.navigate("https://www.google.com")
    page.screenshot(Page.ScreenshotOptions().setPath(File("screenshot.png").toPath()))

    browser.close()
    playwright.close()
}
```

**reflect-config.json**
```json
[
  {
    "name": "com.microsoft.playwright.impl.DriverJar",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": []
      }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.Message",
    "unsafeAllocated": true,
    "fields": [
      { "name": "id" },
      { "name": "guid" },
      { "name": "method" },
      { "name": "params" },
      { "name": "result" },
      { "name": "error" }
    ]
  },
  {
    "name": "com.microsoft.playwright.Browser$NewContextOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.ViewportSize",
    "unsafeAllocated": true,
    "fields": [
      { "name": "width" },
      { "name": "height" }
    ],
    "methods": [
      { "name": "<init>", "parameterTypes": ["int", "int"] }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.HttpHeader",
    "unsafeAllocated": true,
    "fields": [
      { "name": "name" },
      { "name": "value" }
    ]
  },
  {
    "name": "com.microsoft.playwright.options.Timing",
    "unsafeAllocated": true,
    "fields": [
      { "name": "startTime" },
      { "name": "domainLookupStart" },
      { "name": "domainLookupEnd" },
      { "name": "connectStart" },
      { "name": "secureConnectionStart" },
      { "name": "connectEnd" },
      { "name": "requestStart" },
      { "name": "responseStart" },
      { "name": "responseEnd" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedArgument",
    "fields": [
      { "name": "value" },
      { "name": "handles" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedValue",
    "fields": [
      { "name": "n" },
      { "name": "b" },
      { "name": "s" },
      { "name": "v" },
      { "name": "d" },
      { "name": "r" },
      { "name": "a" },
      { "name": "o" },
      { "name": "h" }
    ]
  },
  {
    "name": "com.microsoft.playwright.impl.SerializedValue$O",
    "fields": [
      { "name": "k" },
      { "name": "v" }
    ]
  },
  {
    "name": "com.microsoft.playwright.ElementHandle$ScreenshotOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.Locator$ElementHandleOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  },
  {
    "name": "com.microsoft.playwright.Frame$WaitForSelectorOptions",
    "methods": [
      { "name": "<init>", "parameterTypes": [] }
    ]
  }
]
```

**pom.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>example_playwright</artifactId>
    <groupId>org.example</groupId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>consoleApp</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
    </properties>

    <repositories>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
    </repositories>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.20</version>
                        <extensions>true</extensions>
                        <executions>
                            <execution>
                                <id>build-native</id>
                                <goals>
                                    <goal>compile-no-fork</goal>
                                </goals>
                                <phase>package</phase>
                            </execution>
                            <execution>
                                <id>test-native</id>
                                <goals>
                                    <goal>test</goal>
                                </goals>
                                <phase>test</phase>
                            </execution>
                        </executions>
                        <configuration>
                            <imageName>${project.artifactId}</imageName>
                            <mainClass>MainKt</mainClass>
                            <buildArgs>
                                <arg>--enable-https</arg>
                                <arg>--no-fallback</arg>
                                <arg>--report-unsupported-elements-at-runtime</arg>
                                <arg>--initialize-at-build-time</arg>
                                <arg>--no-server</arg>
                                <arg>-H:IncludeResources=.*</arg>
                                <arg>-H:ReflectionConfigurationFiles=./reflect-config.json</arg>
                            </buildArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.8.0</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <mainClass>MainKt</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>7</source>
                    <target>7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.31.0</version>
        </dependency>
    </dependencies>
</project>
```
