### ISSUE TITLE
Failed to install browsers, exit code: 134

### ISSUE THREAD

**Issue by im-yun** [microsoft/playwright-java#1236]
Playwright Version: 1.31.0
Browser: Firefox or any other

```
java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
        at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
        at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
        at com.microsoft.playwright.Playwright.create(Playwright.java:110)
        at com.microsoft.playwright.Playwright.create(Playwright.java:114)
        at getAuthor(PlaywrightAuthorService.java:27)
        at .lambda$getAuthorById$0(AuthorServiceImpl.java:27)
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:152)
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4440)
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4570)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4422)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4358)
        at com.salesforce.reactorgrpc.stub.ServerCalls.oneToOne(ServerCalls.java:41)

Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 134
        at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:100)
        at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:69)
        at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
        ... 31 common frames omitted
```

The same code works on win-11 so it is something with unbutu-20.04 server edition

I have attempted to delete cache directory, and install again. And also with npx. I also installed all deps

Binaries are downloaded trying to run from cache directory starts them correctly so I'm not sure what the exact issue is.

**Comment by yury-s** [comment]
Can you create a repro based on our [docker image](https://playwright.dev/java/docs/docker)?

**Comment by yury-s** [comment]
You can run with `DEBUG=pw:install` to get some debug logs. Perhaps playwright fails to write into the temp dir or some animalware interferes?

**Comment by v46** [comment]
I ran into the same issue with 1.32.0. Rolling back to 1.30.0 seemed to work fine.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue when you have a repro and link it to this one.
