### ISSUE TITLE
[BUG] Firefox sometimes pops up “Insecure password warning”

### ISSUE THREAD

**Issue by jglick** [microsoft/playwright-java#1240]
### System info
- Playwright Version: v1.31.0
- Operating System: Ubuntu 22.04.2
- Browser: Firefox

### Source code

```java
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Playwright;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
public class PlaywrightBug {
    public static void main(String[] args) throws Exception {
        var proc = new ProcessBuilder("docker", "run", "--rm", "-p", "127.0.0.1:80:8080", "ghcr.io/jglick/authenticated-jenkins:main").inheritIO().start();
        try (
                var playwright = Playwright.create();
                var browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(false));
                var context = browser.newContext();
                var page = context.newPage()) {
            while (!page.navigate("http://jenkins.127.0.0.1.nip.io/login").ok()) {
                System.err.println("Waiting for Jenkins to become ready…");
                Thread.sleep(1000);
            }
            page.getByPlaceholder("Username").fill("admin");
            page.getByPlaceholder("Password").fill("admin");
            // Does not work; label intercepts click: page.getByLabel("Keep me signed in").check()
            page.getByText("Keep me signed in").click();
            page.getByText("Sign in").click();
            assertThat(page.getByText("Welcome to Jenkins!")).isVisible();
        } finally {
            proc.destroy();
        }
        System.exit(0);
    }
}
```

**Steps**
Run the program.
**Expected**
Passes.
**Actual**
Sometimes passes. Sometimes Firefox opens a tab showing https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct which blocks visibility of the login form and prevents the test from proceeding:

```
Exception in thread "main" com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for getByText("Keep me signed in")
  locator resolved to <label for="remember_me">Keep me signed in</label>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for getByText("Keep me signed in")
  locator resolved to <label for="remember_me">Keep me signed in</label>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
    at ProgressController.run (/tmp/playwright-java-1866671914204587060/package/lib/server/progress.js:88:26)
    at Frame.click (/tmp/playwright-java-1866671914204587060/package/lib/server/frames.js:1011:23)
    at FrameDispatcher.click (/tmp/playwright-java-1866671914204587060/package/lib/server/dispatchers/frameDispatcher.js:149:30)
    at DispatcherConnection.dispatch (/tmp/playwright-java-1866671914204587060/package/lib/server/dispatchers/dispatcher.js:319:46)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.FrameImpl.clickImpl(FrameImpl.java:252)
	at com.microsoft.playwright.impl.FrameImpl.lambda$click$8(FrameImpl.java:243)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.FrameImpl.click(FrameImpl.java:243)
	at com.microsoft.playwright.impl.LocatorImpl.click(LocatorImpl.java:123)
	at com.microsoft.playwright.Locator.click(Locator.java:2183)
	at PlaywrightBug.main(PlaywrightBug.java:19)
Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for getByText("Keep me signed in")
  locator resolved to <label for="remember_me">Keep me signed in</label>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for getByText("Keep me signed in")
  locator resolved to <label for="remember_me">Keep me signed in</label>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
    at ProgressController.run (/tmp/playwright-java-1866671914204587060/package/lib/server/progress.js:88:26)
    at Frame.click (/tmp/playwright-java-1866671914204587060/package/lib/server/frames.js:1011:23)
    at FrameDispatcher.click (/tmp/playwright-java-1866671914204587060/package/lib/server/dispatchers/frameDispatcher.js:149:30)
    at DispatcherConnection.dispatch (/tmp/playwright-java-1866671914204587060/package/lib/server/dispatchers/dispatcher.js:319:46)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:199)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:181)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	... 12 more
```

**Comment by jglick** [comment]
The following does _not_ seem to help, despite `about:config` confirming that the preference is set:

```java
setFirefoxUserPrefs(Map.of("security.insecure_password.ui.enabled", false, "security.insecure_field_warning.contextual.enabled", false))
```

perhaps because of https://bugzilla.mozilla.org/show_bug.cgi?id=1773047

**Comment by yury-s** [comment]
Thanks for the test! I can reproduce it locally.
