### ISSUE TITLE
OnPage::request blocks all the threads. on response.body()

### ISSUE THREAD

**Issue by cortizcuellar** [microsoft/playwright-java#1241]
All i need to do is just log the consume on playwright behind the scenes i did something like this.

    page.onResponse(this::logConsumeOnResponseFromPlaywright);

But all the threads late on it gets blocked on .body()

```
    #28 prio=5 os_prio=0 tid=0x000000001f799800 nid=0x1281c runnable [0x0000000028edd000]
     java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000083f87e88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
        at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:68)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:164)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:107)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:108)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:100)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:96)
        at com.microsoft.playwright.impl.ResponseImpl.lambda$body$1(ResponseImpl.java:56)
        at com.microsoft.playwright.impl.ResponseImpl$$Lambda$356/796625608.get(Unknown Source)
        at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
        at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:85)
        at com.microsoft.playwright.impl.ResponseImpl.body(ResponseImpl.java:55)
```

Yep all of them.

![image](https://user-images.githubusercontent.com/85301269/227521191-558df416-0635-4912-9875-2575eb68526f.png)

I was wondering why this? 

I try a different approach sending all the responses to a executorService and allow them to wait a specify time but i dont know why they can't get body() even waiting for 30 seconds.

`08:29:50.159 [pool-13-thread-8] DEBUG ``c.p.h.HeadlessBrowserConfig$DataPerThread.poolConsumeOnResponseFromPlaywrightToExecutor(343) - Could not get body from response:[1653687120] in [30] seconds.`

Indeed only a few of them get the body and i dont know what to do! Is this a bug?

**Comment by yury-s** [comment]
Please follow the issue template to describe your problem and exact steps to reproduce it. With the information in hand we can only guess what you are trying to do and what is not working as expected.

**Comment by cortizcuellar** [comment]
But the stacktrace don't give a hint? i dont know why Response.body() gets block, even after 3 hours the threads gets block.

**Comment by yury-s** [comment]
The stack trace shows normal call sequence, nothing unusual.

**Comment by LucaLis** [comment]
Hi @cortizcuellar! Have you been able to find a solution for this problem?
