### ISSUE TITLE
[BUG] Not able to use Chromium Binary as it gets deleted every time it's used with Browser Closed Error

### ISSUE THREAD

**Issue by navneetyubi** [microsoft/playwright-java#1257]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 12.3 ]
- Browser: [Chromium]
- Java Version: 19

### Source code
**Test file (self-contained)**
```java
import com.microsoft.playwright.*;
import com.microsoft.playwright.options.AriaRole;

public class FirstTest {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions()
                    .setHeadless(false);
            Browser browser = playwright.chromium().launch(launchOptions);
            Page page1 = browser.newPage();
            page1.navigate("https://qa.smartcollect.digital/");
        }
    }
}
```
**POM.XML file (self-contained)**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>CollectionsUIAutomation</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.32.0</version>
        </dependency>
    </dependencies>
    <properties>
        <maven.compiler.source>19</maven.compiler.source>
        <maven.compiler.target>19</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <!-- References to interface static methods are allowed only at source level 1.8 or above -->
                <configuration>
                    <source>9</source>
                    <target>9</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
````
**Steps**
- Simply run the test class file.

**Expected**
Chromium browser should launch and code should start running.

**Actual**
Chromium Binary gets downloaded if its not downloaded already then below error is shown in run console and then chromium binary is deleted from it's download location "/Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/"
--------------------------

```
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Error {
  message='Browser closed.
==================== Browser output: ====================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
============================================================
  name='Error
  stack='Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
============================================================
    at /private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crConnection.js:169:16
    at new Promise (<anonymous>)
    at CRSession.send (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crConnection.js:165:12)
    at CRBrowser.connect (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crBrowser.js:47:35)
    at Chromium._connectToTransport (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/chromium.js:131:33)
    at Chromium._innerLaunch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:128:32)
    at async Chromium._innerLaunchWithRetries (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:86:14)
    at async ProgressController.run (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/progress.js:92:22)
    at async Chromium.launch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:63:21)
    at async BrowserTypeDispatcher.launch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/dispatchers/browserTypeDispatcher.js:35:21)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:52)
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:35)
	at common.FirstTest.main(FirstTest.java:12)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Browser closed.
==================== Browser output: ====================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
============================================================
  name='Error
  stack='Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-galmF9 --remote-debugging-pipe --no-startup-window
<launched> pid=25907
[pid=25907] <process did exit: exitCode=null, signal=SIGKILL>
[pid=25907] starting temporary directories cleanup
============================================================
    at /private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crConnection.js:169:16
    at new Promise (<anonymous>)
    at CRSession.send (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crConnection.js:165:12)
    at CRBrowser.connect (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/crBrowser.js:47:35)
    at Chromium._connectToTransport (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/chromium/chromium.js:131:33)
    at Chromium._innerLaunch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:128:32)
    at async Chromium._innerLaunchWithRetries (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:86:14)
    at async ProgressController.run (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/progress.js:92:22)
    at async Chromium.launch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/browserType.js:63:21)
    at async BrowserTypeDispatcher.launch (/private/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright-java-7003718108946997311/package/lib/server/dispatchers/browserTypeDispatcher.js:35:21)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:226)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:206)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	... 9 more

Process finished with exit code 1
```
--------------------------

**Comment by navneetyubi** [comment]
Same happens when I try to run codegen command: _mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="codegen wikipedia.org"_

`Chromium 112.0.5615.29 (playwright build v1055) downloaded to /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055
navneetsingh.patel@CALTM00678 CollectionsUIAutomation % mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="codegen wikipedia.org"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< org.example:CollectionsUIAutomation >-----------------
[INFO] Building CollectionsUIAutomation 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec:3.1.0:java (default-cli) @ CollectionsUIAutomation ---
[Error: Browser closed.
==================== Browser output: ====================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-kWqDx8 --remote-debugging-pipe --no-startup-window
<launched> pid=26740
[pid=26740] <process did exit: exitCode=null, signal=SIGKILL>
[pid=26740] starting temporary directories cleanup
=========================== logs ===========================
<launching> /Users/navneetsingh.patel/Library/Caches/ms-playwright/chromium-1055/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/rm/km93m6b52h13w07mrr8q2xx80000gq/T/playwright_chromiumdev_profile-kWqDx8 --remote-debugging-pipe --no-startup-window
<launched> pid=26740
[pid=26740] <process did exit: exitCode=null, signal=SIGKILL>
[pid=26740] starting temporary directories cleanup
============================================================]
`

**Comment by navneetyubi** [comment]
> > and then chromium binary is deleted from it's download location
> 
> Playwright does not delete the binary like this. The browser should stay there after download. Most likely you have some antivirus software that removes the browser binaries under your feet while Playwright is running. You'll probably need to add that location to some allow list. See also [this page](https://playwright.dev/java/docs/browsers) in case you want to change the download location.

Is that's the case I am not sure why it's not happening for other browser binary but only for chromium(All binary are stored in the same path). it Also doesn't happens when I do this by setting the channel to Chrome, it's only when I am using pure Chromium.

**Comment by yury-s** [comment]
> Is that's the case I am not sure why it's not happening for other browser binary but only for chromium(All binary are stored in the same path). 

That's weird indeed. You can set a breakpoint at [this line](https://github.com/microsoft/playwright-java/blob/c237fae71ee173aa841d362d05609bd3476d1e1d/driver-bundle/src/main/java/com/microsoft/playwright/impl/driver/jar/DriverJar.java#L95) and check if the browser stays in the cache folder if you don't do anything. You can run with `DEBUG=pw:install` environment variable to see a bit more details about the installation progress.

> it Also doesn't happens when I do this by setting the channel to Chrome, it's only when I am using pure Chromium.

In case of Chrome channel Playwright uses preinstalled Google Chrome binary and does not install it automatically.

**Comment by mxschmitt** [comment]
Closing for now since we were not able to reproduce, its probably caused by anti virus and the issue looks stale.
