### ISSUE TITLE
 Failed to read message from driver, pipe closed.

### ISSUE THREAD

**Issue by AdelaPro2** [microsoft/playwright-java#1276]
### System info
- Playwright Version: 1.33.0
         (<dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.33.0</version>
        </dependency>)
- Operating System: Windows 
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: nodejs V18.16.0, JDK 17

### Source code

```java
public class APP {

    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("http://playwright.dev");
            System.out.println(page.title());
        }
    }
}
```

**error msg**

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (node:net:682:20)
    at Socket._read (node:net:693:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at Socket.read (node:net:749:39)
    at new Socket (node:net:470:12)
    at Object.Socket (node:net:339:41)
    at createSocket (node:internal/child_process:328:14)
    at ChildProcess.spawn (node:internal/child_process:443:23)
    at spawn (node:child_process:757:9)
    at spawnAsync (C:\Temp\playwright-java-7405333757743731671\package\lib\utils\spawnAsync.js:25:44)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4053,
  code: 'ENOTCONN',
  syscall: 'read'
}

Node.js v18.16.0
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:200)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:52)
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:35)
	at com.microsoft.playwright.BrowserType.launch(BrowserType.java:1166)
	at com.trend.asp.executor.APP.main(APP.java:22)
Caused by: java.io.EOFException
	at com.microsoft.playwright.impl.ReaderThread.readIntLE(PipeTransport.java:110)
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:139)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:125)

```

**Comment by AdelaPro2** [comment]
<img width="1366" alt="playwright code" src="https://user-images.githubusercontent.com/38579430/236974874-0d143e0a-4edf-4392-b7e8-c1a78ffd7564.png">
I have debugged and found that an exception occurred while executing code. get() in LoggingSupport. java, but I have checked that the code parameter executePath is correct and exists on my computer;

But I haven't found the specific implementation of code. get(), so can you tell me what the problem is or how to solve it。
C:\Users\username\AppData\Local\ms-playwright\chromium-1045\chrome-win

**Comment by yury-s** [comment]
Looks like playwright fails to start browser at the specified path, try running with more debug logging:
```cmd
set DEBUG=pw:browser
mvn compile exec:java -Dexec.mainClass=APP
```

Can you launch the browser at `C:\Users\username\AppData\Local\ms-playwright\chromium-1045\chrome-win\chrome.exe` manually? There is likely something specific to your environment that prevents the browser from starting.

**Comment by AdelaPro2** [comment]
After setting DEBUG=pw: browser, I found a new line of logs:
browser type is not supported,com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
But I can manually open this browser.

**Comment by AdelaPro2** [comment]
When I run with idea,  the log is:
`2023-05-23T05:53:05.449Z pw:install created DriverJar: C:\windows\playwright-java-7189540653827891366
2023-05-23T05:53:05.450Z pw:install initializing driver
2023-05-23T05:53:07.645Z pw:install extracted driver from jar to C:\windows\playwright-java-7189540653827891366\playwright.cmd
2023-05-23T05:53:08.371Z pw:install Chromium playwright build v1050 is already downloaded.
2023-05-23T05:53:08.372Z pw:install FFMPEG playwright build v1008 is already downloaded.
2023-05-23T05:53:08.373Z pw:install Firefox 109.0 (playwright build v1378) is already downloaded.
2023-05-23T05:53:08.374Z pw:install Webkit 16.4 (playwright build v1792) is already downloaded.
2023-05-23T05:53:08.388Z pw:install driver initialized.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (node:net:682:20)
    at Socket._read (node:net:693:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at Socket.read (node:net:749:39)
    at new Socket (node:net:470:12)
    at Object.Socket (node:net:339:41)
    at createSocket (node:internal/child_process:328:14)
    at ChildProcess.spawn (node:internal/child_process:443:23)
    at spawn (node:child_process:757:9)
    at spawnAsync (C:\Windows\playwright-java-7189540653827891366\package\lib\utils\spawnAsync.js:25:44)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4053,
  code: 'ENOTCONN',
  syscall: 'read'
}
Node.js v18.14.0
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:175)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:119)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:52)
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:44)
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:35)
	at com.trend.asp.APP.main(APP.java:22)
Caused by: java.io.EOFException
	at com.microsoft.playwright.impl.ReaderThread.readIntLE(PipeTransport.java:110)
	at com.microsoft.playwright.impl.ReaderThread.readMessage(PipeTransport.java:139)
	at com.microsoft.playwright.impl.ReaderThread.run(PipeTransport.java:125)`



Process finished with exit code 1

But when I run cmd in Idea's terminal， Playwright is right. 
`The log is 2023-05-23T05:51:06.985Z pw:install created DriverJar: C:\Users\dulce_li\AppData\Local\Temp\playwright-java-2837814283618987839
2023-05-23T05:51:06.986Z pw:install initializing driver
2023-05-23T05:51:08.937Z pw:install extracted driver from jar to C:\Users\dulce_li\AppData\Local\Temp\playwright-java-2837814283618987839\playwright.cmd
  pw:install Chromium playwright build v1050 is already downloaded. +0ms
  pw:install FFMPEG playwright build v1008 is already downloaded. +3ms
  pw:install Firefox 109.0 (playwright build v1378) is already downloaded. +2ms
  pw:install Webkit 16.4 (playwright build v1792) is already downloaded. +2ms
2023-05-23T05:51:09.689Z pw:install driver initialized.
  pw:browser <launching> C:\Users\dulce_li\AppData\Local\ms-playwright\webkit-1792\Playwright.exe --inspector-pipe --disable-accelerated-compositing --no-startup-window +0ms
  pw:browser <launched> pid=30760 +18ms
Trend Micro? Worry-Free? Business Security Services
  pw:browser [pid=30760] <gracefully close start> +7s
  pw:browser [pid=30760] <process did exit: exitCode=0, signal=null> +66ms
  pw:browser [pid=30760] starting temporary directories cleanup +1ms
  pw:browser [pid=30760] finished temporary directories cleanup +9ms
  pw:browser [pid=30760] <gracefully close end> +0ms`

**Comment by AdelaPro2** [comment]
I uninstall the idea 2022.3.3  and install the Idea 2023.1.2, and this problem has not arisen.
I think it may be because I have installed some plugins in the idea.
