### ISSUE TITLE
[BUG] Null browser reference in browserContext if context is launched persistently

### ISSUE THREAD

**Issue by psyopguy** [microsoft/playwright-java#1291]
Exception (while trying to get page PDF) :
```java
 java.lang.NullPointerException
	at com.microsoft.playwright.impl.PageImpl.pdfImpl(PageImpl.java:966)
	at com.microsoft.playwright.impl.PageImpl.lambda$pdf$59(PageImpl.java:962)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.PageImpl.pdf(PageImpl.java:962)`
``` 

Version : **playwright 1.33.0**

Easley reproducible : 
```java
Playwright playwright = Playwright.create();
BrowserType browserType = playwright.chromium();
BrowserContext browserContext = null;
Path userDataDir = Paths.get(PROJECT_PATH+"\\data\\browserProfile");
browserContext = browserType.launchPersistentContext(
                    userDataDir,
                    new BrowserType.LaunchPersistentContextOptions()
                            .setHeadless(false)
                            .setViewportSize(1920 , (int) Math.round(1080 ))
                            .setArgs(createChromeFlags())
                            .setIgnoreDefaultArgs(asList("--enable-automation","--disable-extensions","--no-sandbox"))
            );
page.navigate("SOME URL");
page.emulateMedia(new age.EmulateMediaOptions().setMedia(Media.SCREEN));
page.pdf(new Page.PdfOptions().setPath(Paths.get("test.pdf")));
``` 

Even if "launchPersistent" is not supported in chrome (don't understand why I saw that somewhere) this NPE should not happen since the page works fine and the exception can be avoided (The code checkup if (!browserContext.browser().isChromium())  can be optional \ handled better )

**Comment by psyopguy** [comment]
Created a temporary bypass until the library code is changed : 

```java
public static byte[] pdfImpl(PageImpl p, Page.PdfOptions options) {
        try {
            if (options == null) {
                options = new Page.PdfOptions();
            }

            //JsonObject params = gson().toJsonTree(options).getAsJsonObject();
            Class<?> SerializationClazz = Class.forName("com.microsoft.playwright.impl.Serialization");
            Method gsonMethod = SerializationClazz.getDeclaredMethod("gson");
            gsonMethod.setAccessible(true);
            JsonObject params = ((Gson) gsonMethod.invoke(null)).toJsonTree(options).getAsJsonObject();
            params.remove("path");

            //p.sendMessage("pdf", params).getAsJsonObject();
            Class<?> channelOwnerClazz = Class.forName("com.microsoft.playwright.impl.ChannelOwner");
            Method method = channelOwnerClazz.getDeclaredMethod("sendMessage", String.class, JsonObject.class);
            method.setAccessible(true);
            JsonObject json = ((JsonElement) method.invoke(p, "pdf", params)).getAsJsonObject();

            byte[] buffer = Base64.getDecoder().decode(json.get("pdf").getAsString());
            if (options.path != null) {
                //Utils.writeToFile(buffer, options.path);
                Class<?> utilsClazz = Class.forName("com.microsoft.playwright.impl.Utils");
                Method writeToFileMethod = utilsClazz.getDeclaredMethod("writeToFile", byte[].class, Path.class);
                writeToFileMethod.setAccessible(true);
                writeToFileMethod.invoke(null,buffer, options.path);
            }

            return buffer;
        }catch (Exception e){
            log.error("Error while trying to save pdf",e);
            return null;
        }
    }
```
