### ISSUE TITLE
[BUG] Assertion failed on Locator.expect with timeout 5000ms even though wait for was for 10000 ms

### ISSUE THREAD

**Issue by ecarmiel** [microsoft/playwright-java#1297]
### System info
- Playwright Version: [v1.34.0]
- Operating System:  Windows 11
- Browser:  Chromium
- Other info:
I work on internal website and writing automation.
I'm trying to validate an API that webapp is running which sometimes takes more than 5 seconds.
After 5 seconds some message should show up or a button should be enabled .
But even if i change the default timeout or wait for more than 10 seconds , it times out after 5 seconds.

### Source code

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```java

next.waitFor(new Locator.WaitForOptions().setState(WaitForSelectorState.VISIBLE).setTimeout(30000));
assertThat(page.getByText(good_News,new Page.GetByTextOptions().setExact(true))).isVisible();
assertThat(next).isEnabled();

**Steps**
- Run code
- 

**Expected**
Button to enabled after more than 5 seconds . 

**Actual**

Call log:
Locator.expect with timeout 5000ms
waiting for getByText("Next")
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
  locator resolved to <button disabled class="button_btn__i3vLE button_btn--pr…>Next</button>
  unexpected value "disabled"
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:68)
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:50)
	at com.microsoft.playwright.impl.LocatorAssertionsImpl.expectTrue(LocatorAssertionsImpl.java:352)
	at com.microsoft.playwright.impl.LocatorAssertionsImpl.isEnabled(LocatorAssertionsImpl.java:320)
	at com.microsoft.playwright.assertions.LocatorAssertions.isEnabled(LocatorAssertions.java:559)
	at org.example.Main.main(Main.java:39)

**Comment by yury-s** [comment]
You set timeout 30s for waitFor but the exception is thrown from isEnabled. If you want isEnabled to wait up to 10s change the code like this:

```java
    assertThat(next).isEnabled(new LocatorAssertions.IsEnabledOptions().setTimeout(10_000));
```
If you want to change default timeout for all methods, you can use [BrowserContext.setTimeout](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-set-default-timeout).
