### ISSUE TITLE
[BUG] com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed

### ISSUE THREAD

**Issue by vasthan** [microsoft/playwright-java#1301]
### System info
- Playwright Version: 1.34.0
- Operating System: Enterprise Linux Server 7.2
- Browser: Chromium
- Other info: 
i download chromium-linux.zip, then unzip it, place at
![image](https://github.com/microsoft/playwright-java/assets/31793991/6ad62cd8-7cee-4a4e-8a11-2c51b4260a20)

### Source code
```java
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import com.microsoft.playwright.*;

public class PlayWrightApp {

    public static void main(String[] args) {
        Map<String, String> env = new HashMap<>();
        env.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
        // linux
        env.put("PLAYWRIGHT_BROWSERS_PATH", "/home/admin/software/pw-browsers");
        // mac
        // env.put("PLAYWRIGHT_BROWSERS_PATH", "/usr/local/software/pw-browsers");

        Playwright.CreateOptions createOptions = new Playwright.CreateOptions();
        createOptions.setEnv(env);

        try (Playwright playwright = Playwright.create(createOptions)) {
            BrowserType browserType = playwright.chromium();

            try (Browser browser = browserType.launch()) {
                BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                    .setViewportSize(2560, 1440).setDeviceScaleFactor(2));

                Page page = context.newPage();
                page.navigate("http://xxx/chart/get");

                Path path = Paths.get("/home/admin/xxx/output.png");
                Page.ScreenshotOptions screenshotOptions = new Page.ScreenshotOptions()
                    .setPath(path);
                page.screenshot(screenshotOptions);
            }
        }
    }
}
```

### log
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
/tmp/playwright-java-6277895080476520163/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/playwright-java-6277895080476520163/node)
/tmp/playwright-java-6277895080476520163/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/playwright-java-6277895080476520163/node)
/tmp/playwright-java-6277895080476520163/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/playwright-java-6277895080476520163/node)
/tmp/playwright-java-6277895080476520163/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/playwright-java-6277895080476520163/node)
/tmp/playwright-java-6277895080476520163/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/playwright-java-6277895080476520163/node)
/tmp/playwright-java-6277895080476520163/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/playwright-java-6277895080476520163/node)
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at com.microsoft.playwright.impl.WriterThread.run(PipeTransport.java:167)
java.io.IOException: Stream closed
        at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
        at java.io.OutputStream.write(OutputStream.java:116)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at com.microsoft.playwright.impl.PipeTransport.close(PipeTransport.java:93)
        at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:71)
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:200)
        at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:109)
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
        at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:82)
        at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:177)
        at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:52)
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
        at com.microsoft.playwright.Playwright.create(Playwright.java:110)
        at com.adc.demo.test.uln.PlayWrightApp.main(PlayWrightApp.java:25)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
        at java.lang.Thread.run(Thread.java:874)
[WARNING] 
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
    at com.microsoft.playwright.impl.PipeTransport.poll (PipeTransport.java:75)
    at com.microsoft.playwright.impl.Connection.processOneMessage (Connection.java:200)
    at com.microsoft.playwright.impl.ChannelOwner.runUntil (ChannelOwner.java:109)
    at com.microsoft.playwright.impl.Connection.sendMessage (Connection.java:126)
    at com.microsoft.playwright.impl.ChannelOwner.sendMessage (ChannelOwner.java:102)
    at com.microsoft.playwright.impl.Connection$Root.initialize (Connection.java:82)
    at com.microsoft.playwright.impl.Connection.initializePlaywright (Connection.java:177)
    at com.microsoft.playwright.impl.PlaywrightImpl.createImpl (PlaywrightImpl.java:52)
    at com.microsoft.playwright.impl.PlaywrightImpl.create (PlaywrightImpl.java:35)
    at com.microsoft.playwright.Playwright.create (Playwright.java:110)
    at com.adc.demo.test.uln.PlayWrightApp.main (PlayWrightApp.java:25)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:874)
Caused by: java.io.EOFException
    at com.microsoft.playwright.impl.ReaderThread.readIntLE (PipeTransport.java:110)
    at com.microsoft.playwright.impl.ReaderThread.readMessage (PipeTransport.java:139)
    at com.microsoft.playwright.impl.ReaderThread.run (PipeTransport.java:125)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.885 s
[INFO] Finished at: 2023-06-09T20:17:50+08:00

**Comment by mxschmitt** [comment]
>  GLIBC_2.27' not found 

This means that you are using an unsupported Linux distribution, see here for our requirements: https://playwright.dev/java/docs/intro#system-requirements

You could use Docker to workaround it, but we generally recommend using an up2date and supported Linux distribution like Ubuntu 22.
