### ISSUE TITLE
[BUG] v1.35.0 fails to create driver inside v1.35.0 based container / on M1 mac error: This command is not for general use and should only be run as the result of a call to ProcessBuilder.start() or Runtime.exec() in a java application

### ISSUE THREAD

**Issue by paulwwisl** [microsoft/playwright-java#1308]
### System info
- Playwright Version: [v1.35]
- Operating System: [Ubuntu 2022.4 inside docker on M1 mac]
- Browser: [Chromium]
- Other info:

When using playwright-java https://github.com/microsoft/playwright-java
in Java/Spring

```java
  @PostConstruct
  void init(){
    LOGGER.info("Initializinig Playwright with Chromium ...");
    Playwright playwright = Playwright.create();
    browser = playwright.chromium().launch(); // Page.pdf only supported in headless Chromium
  }
```

I get Exception (See log below). I understand that I need to find a way to look inside running container temp .sh file, I would expect Java app using playwright-java running inside microsoft.com/playwright/java container (of the same v1.35.0) should just work.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'playwrightPdfConverterService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to create driver
2023-06-14T15:05:31.174236127Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
2023-06-14T15:05:31.174238335Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
2023-06-14T15:05:31.174240377Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
2023-06-14T15:05:31.174242293Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
2023-06-14T15:05:31.174244168Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2023-06-14T15:05:31.174246085Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2023-06-14T15:05:31.174250960Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2023-06-14T15:05:31.174286252Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2023-06-14T15:05:31.174289335Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2023-06-14T15:05:31.174291252Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
2023-06-14T15:05:31.174293168Z 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
2023-06-14T15:05:31.174296127Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
2023-06-14T15:05:31.174298168Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
2023-06-14T15:05:31.174300085Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
2023-06-14T15:05:31.174302293Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
2023-06-14T15:05:31.174304168Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
2023-06-14T15:05:31.174306002Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
2023-06-14T15:05:31.174307793Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
2023-06-14T15:05:31.174309543Z 	at com.company.pdf.Application.main(Application.java:12)
2023-06-14T15:05:31.174311293Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-14T15:05:31.174313085Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-14T15:05:31.174314918Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-14T15:05:31.174316752Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-14T15:05:31.174318460Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2023-06-14T15:05:31.174320293Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
2023-06-14T15:05:31.174322085Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2023-06-14T15:05:31.174323793Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2023-06-14T15:05:31.174325585Z Caused by: java.lang.RuntimeException: Failed to create driver
2023-06-14T15:05:31.174327293Z 	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
2023-06-14T15:05:31.174330835Z 	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
2023-06-14T15:05:31.174334460Z 	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
2023-06-14T15:05:31.174340127Z 	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
2023-06-14T15:05:31.174343460Z 	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
2023-06-14T15:05:31.174345335Z 	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
2023-06-14T15:05:31.174347085Z 	at com.company.pdf.converter.PlaywrightPdfConverterService.init(PlaywrightPdfConverterService.java:29)
2023-06-14T15:05:31.174348835Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-06-14T15:05:31.174429543Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-06-14T15:05:31.174448960Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-06-14T15:05:31.174451293Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-06-14T15:05:31.174453127Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
2023-06-14T15:05:31.174455127Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
2023-06-14T15:05:31.174457127Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
2023-06-14T15:05:31.174458960Z 	... 26 common frames omitted
2023-06-14T15:05:31.174460460Z Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-7667674547892745859/playwright.sh": error=0, Failed to exec spawn helper: pid: 36, exit value: 1
2023-06-14T15:05:31.174462377Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
2023-06-14T15:05:31.174464043Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
2023-06-14T15:05:31.174465585Z 	at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:93)
2023-06-14T15:05:31.174467252Z 	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:69)
2023-06-14T15:05:31.174468877Z 	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
2023-06-14T15:05:31.174472752Z 	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
2023-06-14T15:05:31.174475377Z 	... 39 common frames omitted
2023-06-14T15:05:31.174477002Z Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 36, exit value: 1
2023-06-14T15:05:31.174478668Z 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
2023-06-14T15:05:31.174480335Z 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
2023-06-14T15:05:31.174482127Z 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
2023-06-14T15:05:31.174496252Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
2023-06-14T15:05:31.174498960Z 	... 44 common frames omitted
2023-06-14T15:05:31.174500585Z 
```

### Source code

```java
  @PostConstruct
  void init(){
    LOGGER.info("Initializinig Playwright with Chromium ...");
    Playwright playwright = Playwright.create();
    browser = playwright.chromium().launch(); // Page.pdf only supported in headless Chromium
  }
```

Dockerfile
```dockerfile
FROM mcr.microsoft.com/playwright/java:v1.35.0-jammy-amd64
# Ubuntu 22.04-based image with java 17, mvn 3.8.8
# and chromium-1064  ffmpeg-1009  firefox-1408  webkit-1848
# See https://github.com/microsoft/playwright-java/blob/main/utils/docker/Dockerfile.jammy
# For tags and available platform see
# https://mcr.microsoft.com/en-us/product/playwright/java/tags

WORKDIR /opt

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} ./pdf-service.jar



# run server
EXPOSE 8300
ENTRYPOINT ["java","-jar","./pdf-service.jar"]
```

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    Playwright playwright = Playwright.create();
    browser = playwright.chromium().launch();
    }
  }
}
```

**Steps**
- [Run any Playwright app within docker]
- [...]

**Expected**

Playwright can initialise inside docker container based on mcr.microsoft.com/playwright/java:v1.35.0-jammy-amd64

**Actual**

Failure inside docker

Also asked on https://stackoverflow.com/questions/76475219/playwright-java-inside-docker-runtimeexception-failed-to-create-driver

**Comment by yury-s** [comment]
Works fine for me. Can you share full repro that we could run locally?

**Comment by paulwwisl** [comment]
> Works fine for me. Can you share full repro that we could run locally?
This is not open project, so I cannot share.
And you can point to a open project that has Java app using playwright-java running in container based on `mcr.microsoft.com/playwright/java` image?

OK, how to use `DEBUG=pw:install` is answered in https://github.com/microsoft/playwright/issues/2575
so trying to follow driver init...

> 2023-06-15T08:25:59.675Z pw:install created DriverJar: /var/folders/l3/h_xhm8bj0_142_f1ztk52n5r0000gp/T/playwright-java-904172740252735108

```
$ ls /var/folders/l3/h_xhm8bj0_142_f1ztk52n5r0000gp/T/playwright-java-904172740252735108
LICENSE		node		package		playwright.sh
$ less /var/folders/l3/h_xhm8bj0_142_f1ztk52n5r0000gp/T/playwright-java-904172740252735108/playwright.sh

#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
if [ -z "$PLAYWRIGHT_NODEJS_PATH" ]; then
  PLAYWRIGHT_NODEJS_PATH="$SCRIPT_PATH/node"
fi
"$PLAYWRIGHT_NODEJS_PATH" "$SCRIPT_PATH/package/lib/cli/cli.js" "$@"
/var/folders/l3/h_xhm8bj0_142_f1ztk52n5r0000gp/T/playwright-java-904172740252735108/playwright.sh (END)
```

Re-checking logs I noticed error like
`This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application`


```
2023-06-15 12:37:08.488 user:- trace:- path:-  INFO 1 --- [           main] c.t.p.c.PlaywrightPdfConverterService    : Initializing Playwright with Chromium ...
2023-06-15T12:37:10.423380629Z This command is not for general use and should only be run as the result of a call to
2023-06-15T12:37:10.424087504Z ProcessBuilder.start() or Runtime.exec() in a java application
2023-06-15T12:37:10.441221504Z 2023-06-15 12:37:10.438 user:- trace:- path:-  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'playwrightPdfConverterService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Failed to create driver
2023-06-15T12:37:10.484409338Z 
```

**Comment by paulwwisl** [comment]
In simpler words, it way be Java problem (when running within docker),
but I cannot locate where this message comes from:

> This command is not for general use and should only be run as the result of a call to

And it happens before any `pw:install` specific output could happen, 

    LOGGER.info("Initializing Playwright with Chromium ...");
    Playwright playwright = Playwright.create();

**Comment by paulwwisl** [comment]
I created https://github.com/paulwwisl/playwright-java-example-in-docker

When running the full log is like

```
2023-06-16T14:58:19.577553426Z 2023-06-16T14:58:19.574Z pw:install created DriverJar: /tmp/playwright-java-12548612016051837911
2023-06-16T14:58:19.577605509Z 2023-06-16T14:58:19.577Z pw:install initializing driver
2023-06-16T14:58:20.360761176Z 2023-06-16T14:58:20.360Z pw:install extracted driver from jar to /tmp/playwright-java-12548612016051837911/playwright.sh
2023-06-16T14:58:20.361512093Z Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
2023-06-16T14:58:20.361519968Z 2023-06-16T14:58:20.361Z pw:install driver initialized.
2023-06-16T14:58:20.378470176Z This command is not for general use and should only be run as the result of a call to
2023-06-16T14:58:20.378483260Z ProcessBuilder.start() or Runtime.exec() in a java application
2023-06-16T14:58:20.379560093Z Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to launch driver
2023-06-16T14:58:20.380252468Z 	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:57)
2023-06-16T14:58:20.380262676Z 	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
2023-06-16T14:58:20.380264801Z 	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
2023-06-16T14:58:20.380266676Z 	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
2023-06-16T14:58:20.380268510Z 	at com.example.PlaywrightExampleApp.main(PlaywrightExampleApp.java:8)
2023-06-16T14:58:20.380996426Z Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-12548612016051837911/playwright.sh": error=0, Failed to exec spawn helper: pid: 26, exit value: 1
2023-06-16T14:58:20.381005676Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
2023-06-16T14:58:20.381008051Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
2023-06-16T14:58:20.381119510Z 	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:50)
2023-06-16T14:58:20.381133176Z 	... 4 more
2023-06-16T14:58:20.381208843Z Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 26, exit value: 1
2023-06-16T14:58:20.381215843Z 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
2023-06-16T14:58:20.381217718Z 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
2023-06-16T14:58:20.381219676Z 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
2023-06-16T14:58:20.381221510Z 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
2023-06-16T14:58:20.381223718Z 	... 6 more
```

**Comment by paulwwisl** [comment]
We, we run everything and tests on servers, which are amd64

And had problem before, while trying to have own Dockerfile and installing browser on arm64.
That time switching everything to platform=linux/amd64 did help.

For this ticket it seems the resolution is to just take note,
if one sees error like

> This command is not for general use and should only be run as the result of a call to ProcessBuilder.start() or Runtime.exec() in a java application

that is mac Apple Silicon related. I don't think anything can be done within this repo,
as it seems to be JDK issue

**Comment by yury-s** [comment]
Closing per the comment above.
