### ISSUE TITLE
[BUG]  java code error log  system：linux version 3.10.0-1160.62.1.el7.x86_64 

### ISSUE THREAD

**Issue by niqiuboom** [microsoft/playwright-java#1321]
java.lang.RuntimeException: Failed to install browsers, exit code: 1
	at com.microsoft.playwright.impl.driver.jar.DriverJar.installBrowsers(DriverJar.java:100)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:69)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
	at com.mirattery.baasapi.repository.AysncLarkRepository.test(AysncLarkRepository.java:356)

**Comment by mxschmitt** [comment]
Which Linux distribution are you using? This looks not like a supported Linux distribution: https://playwright.dev/java/docs/intro#system-requirements

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
