### ISSUE TITLE
[BUG] TimeoutError thrown when attempting to take screenshot within onDialog handler

### ISSUE THREAD

**Issue by mrokitka** [microsoft/playwright-java#1325]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**
Page Javascript:
```javascript
confirm("Are you sure that you want to delete the file?");
```
Java:
```java
final Boolean[] dialogProcessed = new Boolean[1];
dialogProcessed[0] = false;
page.onDialog(dialog -> {
  //this prints as expected
  System.out.println("Dialog dismissed");
  //hangs here
  page.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("foo.png"));
  dialogProcessed[0] = true;
  dialog.dismiss();
});
pageModel.clickDeleteButton();
//moving the sshot call to this line does not result in timeout, but it does not visually contain the dialog either
page.waitForCondition(() -> dialogProcessed[0] == true);
```

**Steps**
- [Run the test]

**Expected**

Screenshot taken showing the javascript confirmation dialog

**Actual**

Error stacktrace:
```java
com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
    at ProgressController.run (C:\Users\mike.r\AppData\Local\Temp\playwright-java-12589068589396836453\package\lib\server\progress.js:88:26)
    at Page.screenshot (C:\Users\mike.r\AppData\Local\Temp\playwright-java-12589068589396836453\package\lib\server\page.js:436:23)
    at PageDispatcher.screenshot (C:\Users\mike.r\AppData\Local\Temp\playwright-java-12589068589396836453\package\lib\server\dispatchers\pageDispatcher.js:200:32)
    at DispatcherConnection.dispatch (C:\Users\mike.r\AppData\Local\Temp\playwright-java-12589068589396836453\package\lib\server\dispatchers\dispatcher.js:312:46)
}

	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)
	at com.microsoft.playwright.impl.PageImpl.screenshotImpl(PageImpl.java:1094)
	at com.microsoft.playwright.impl.PageImpl.lambda$screenshot$65(PageImpl.java:1038)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:87)
	at com.microsoft.playwright.impl.PageImpl.screenshot(PageImpl.java:1038)
```

**Comment by yury-s** [comment]
Playwright screenshot of native browser UI elements except for the web content, so you wouldn't see the dialog on the screenshot. Also screenshots are while a modal dialog is open are not supported. You can take screenshot only after the dialog has been handled.

**Comment by mrokitka** [comment]
Can this be documented somewhere?  I wasn't aware this was not supported.
