### ISSUE TITLE
[BUG]: com.microsoft.playwright.TimeoutError: Error { message='Timeout 60000ms exceeded.

### ISSUE THREAD

**Issue by tejaswikommineni** [microsoft/playwright-java#1415]
having an issue while getting the id of the input.

solutions tried:
I tried to add page.locator("#txtUserID").waitFor(new Locator.WaitForOptions().setState(WaitForSelectorState.ATTACHED).setTimeout(60000));

solution code:

```java
  playwright = Playwright.create();
        {
            browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(true));

            BrowserContext context = browser.newContext(new Browser.NewContextOptions()
                    .setIgnoreHTTPSErrors(true));
            // Create a new page in a pristine context.
            context.setDefaultTimeout(60000);
            page = context.newPage();
            page.setDefaultTimeout(16000);
  page.navigate("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    page.locator("#txtUserID").waitFor(new Locator.WaitForOptions().setState(WaitForSelectorState.ATTACHED).setTimeout(60000));
}
```

```
com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator("#txtUserID")
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator("#txtUserID")
============================================================
    at ProgressController.run (/tmp/playwright-java-13819628035945347551/package/lib/server/progress.js:88:26)
    at Frame.waitForSelector (/tmp/playwright-java-13819628035945347551/package/lib/server/frames.js:618:23)
    at FrameDispatcher.waitForSelector (/tmp/playwright-java-13819628035945347551/package/lib/server/dispatchers/frameDispatcher.js:103:103)
    at DispatcherConnection.dispatch (/tmp/playwright-java-13819628035945347551/package/lib/server/dispatchers/dispatcher.js:313:46)
}
	at app//com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52)
	at app//com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:111)
	at app//com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:126)
	at app//com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:102)

```

**Comment by yury-s** [comment]
The element with locator `#txtUserID` is not in the page. Try following [debugging tools](https://playwright.dev/java/docs/debug) and recording [traces](https://playwright.dev/java/docs/trace-viewer-intro) if you can inspect the page live. If you think there is a bug in playwright, please attach a repro that would demonstrate it (page and test).
