### ISSUE TITLE
Failed to create driver in springboot3.2

### ISSUE THREAD

**Issue by kukume** [microsoft/playwright-java#1434]
Windows and debian both show this error.
The playwright version is `1.40.0`
Build a jar with SpringBoot 3.2 build plugin,  then execute `java -jar xx.jar`,
and throw a exception in code `Playwright.create()`. SpringBoot 3.1 have no exception.
```
java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105) ~[driver-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57) ~[driver-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45) ~[playwright-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35) ~[playwright-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.Playwright.create(Playwright.java:110) ~[playwright-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.Playwright.create(Playwright.java:114) ~[playwright-1.40.0.jar!/:1.40.0]
        at me.kuku.api.utils.PlaywrightUtils$playwright$2.invoke(PlaywrightUtils.kt:14) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.utils.PlaywrightUtils$playwright$2.invoke(PlaywrightUtils.kt:13) ~[!/:1.0-SNAPSHOT]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.9.21.jar!/:1.9.21-release-633]
        at me.kuku.api.utils.PlaywrightUtils.getPlaywright(PlaywrightUtils.kt:13) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.utils.PlaywrightUtils.browser(PlaywrightUtils.kt:20) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.utils.PlaywrightUtils.browser$default(PlaywrightUtils.kt:17) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.logic.NodeSeekLogic.sign(NodeSeekLogic.kt:88) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.logic.NodeSeekLogic$sign$1.invokeSuspend(NodeSeekLogic.kt) ~[!/:1.0-SNAPSHOT]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.21.jar!/:1.9.21-release-633]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-jvm-1.7.3.jar!/:na]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.101.Final.jar!/:4.1.101.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296) ~[ktor-server-netty-jvm-2.3.5.jar!/:2.3.5]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar!/:4.1.101.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.util.zip.ZipException: read CEN tables failed
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1561) ~[jdk.zipfs:na]
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179) ~[jdk.zipfs:na]
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:na]
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106) ~[jdk.zipfs:na]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339) ~[na:na]
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288) ~[na:na]
        at com.microsoft.playwright.impl.driver.jar.DriverJar.initFileSystem(DriverJar.java:111) ~[driver-bundle-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.driver.jar.DriverJar.extractDriverToTempDir(DriverJar.java:127) ~[driver-bundle-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:66) ~[driver-bundle-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64) ~[driver-1.40.0.jar!/:1.40.0]
        at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101) ~[driver-1.40.0.jar!/:1.40.0]
        ... 24 common frames omitted
```
In stack
```
 at me.kuku.api.utils.PlaywrightUtils$playwright$2.invoke(PlaywrightUtils.kt:14) ~[!/:1.0-SNAPSHOT]
        at me.kuku.api.utils.PlaywrightUtils$playwright$2.invoke(PlaywrightUtils.kt:13) ~[!/:1.0-SNAPSHOT]
```
code is
```
    val playwright: Playwright by lazy {
        Playwright.create()
    }
```

**Comment by yury-s** [comment]
We don't officially support spring boot loader, but it looks like there is a problem with how the driver is packaged and extracted from the zip: ` java.util.zip.ZipException: read CEN tables failed`. Perhaps something have changed in the zip fs or how the resources are packaged? Can you share a repro?

**Comment by kukume** [comment]
repro: https://minio.kuku.me/kuku/playwright-1.0-SNAPSHOT.jar

**Comment by yury-s** [comment]
We cannot debug a jar file, by repro I meant source code of a minimal project. Try debugging what's going on during the unzip (FileSystems.newFileSystem), why it is failing when updating SpringBoot 3.1 -> 3.2. Since playwright didn't change, it has something to do with the spring boot version and your build configuration.

**Comment by dgozman** [comment]
@kukume Unfortunately, supporting `SpringBoot` loader is out of scope of Playwright. If you manage to figure out a fix, consider posting the solution here for others to benefit.

**Comment by fairjm** [comment]
this is a spring boot bug.
see:
https://github.com/spring-projects/spring-boot/issues/38595
