### ISSUE TITLE
[BUG] - Error thrown when uploading a file with 1.41.0 version

### ISSUE THREAD

**Issue by hamza-amami** [microsoft/playwright-java#1460]
### System info
- Playwright Version: [v1.40.0] & [v1.41.0] 
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

Either this : 

`page.locator(PROFILE_PICTURE_UPLOAD.getSelector()).setInputFiles(Paths.get(path))`

Or this 

```
FileChooser fileChooser = page.waitForFileChooser(() -> page.locator(PROFILE_PICTURE_UPLOAD.getSelector()).click());
fileChooser.setFiles(Paths.get(path));
```
There's an error thrown : 

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsJsonArray()" because the return value of "com.google.gson.JsonObject.get(String)" is null

	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.getStepNameForSetInputFiles(ChannelOwnerAspect.java:138)
	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.getStepName(ChannelOwnerAspect.java:172)
	at io.github.uchagani.allure.playwright.ChannelOwnerAspect.beforeActionMethods(ChannelOwnerAspect.java:79)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:105)
	at com.microsoft.playwright.impl.ElementHandleImpl.setInputFilesImpl(ElementHandleImpl.java:474)
	at com.microsoft.playwright.impl.FileChooserImpl.lambda$setFiles$0(FileChooserImpl.java:62)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:89)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.FileChooserImpl.setFiles(FileChooserImpl.java:61)
	at com.microsoft.playwright.impl.FileChooserImpl.setFiles(FileChooserImpl.java:56)
	at com.microsoft.playwright.FileChooser.setFiles(FileChooser.java:88)
```

**Comment by yury-s** [comment]
The exception is thrown from `io.github.uchagani.allure.playwright.ChannelOwnerAspect.getStepNameForSetInputFiles` which is not a part of Playwright, please file a bug in the corresponding repository instead.

cc @uchagani
