### ISSUE TITLE
[Bug]: Error: Cannot find module './../../package.json'

### ISSUE THREAD

**Issue by pm20390** [microsoft/playwright-java#1498]
### Version

1.41.0

### Steps to reproduce

Run application. Use the same page to perform multiple scraping operations. After ~50 operations I get the following error:
`ode:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module './../../package.json'
Require stack:
- /private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/utils/userAgent.js
- /private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/utils/index.js
- /private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/cli/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at getPlaywrightVersion (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/utils/userAgent.js:91:54)
    at HarTracer.stop (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/server/har/harTracer.js:414:54)
    at Tracing.abort (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/server/trace/recorder/tracing.js:202:21)
    at CRBrowserContext._didCloseInternal (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/server/browserContext.js:191:18)
    at CRBrowserContext._browserClosed (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/server/browserContext.js:183:10)
    at CRBrowser._didClose (/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/server/browser.js:109:52) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/utils/userAgent.js',
    '/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/utils/index.js',
    '/private/var/folders/cj/fs1nn9jd741_03j7ylgywq7r0000gn/T/playwright-java-87147501056601284/package/lib/cli/cli.js'
  ]
}

Node.js v20.11.0`

This is super critical for us as it is failing continuously and there seems to be no resolution.

### Expected behavior

Explanation for the error and resolution. There is no way to catch this error, it just prints to console.

### Actual behavior

Mentioned above

### Environment

Operating System: Mac OS Ventura 13.2.1
Browser: Chromium
Java Version: 20
Maven: 4.0.0
Playwright: 1.41.0

**Comment by pm20390** [comment]
Ah, our main thread in a JUnit test was being garbage collected thus causing the temp files to be removed. Would be good to get a more descriptive error message at some point, but this is a non-issue.

**Comment by Theiaz** [comment]
Getting the same error, how did u solve this issue?

**Comment by pm20390** [comment]
> Getting the same error, how did u solve this issue?

Make sure your main thread doesn't terminate if you're running playwright in a separate thread....e.g. `Thread.currentThread().join();`

**Comment by lnhrdt** [comment]
> Getting the same error, how did u solve this issue?

For us the solution was to call `close()` on our active Playwright instance in a cleanup/after function, to align with our test lifecycle.
https://playwright.dev/java/docs/api/class-playwright#playwright-close
