### ISSUE TITLE
How to use jdk8 within Docker image

### ISSUE THREAD

**Issue by yidasanqian** [microsoft/playwright-java#1574]
The image version I am utilizing is `mcr.microsoft.com/playwright/java:v1.43.0-jammy`, although it employs openjdk21.

cause :
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2cbb3d47
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 95 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2cbb3d47
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:512)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:368)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:129)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:807)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:477)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:472)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:464)
        at org.redisson.codec.FstCodec.<init>(FstCodec.java:182)
        at org.redisson.config.Config.<init>(Config.java:105)
        at org.redisson.Redisson.<init>(Redisson.java:57)
        at org.redisson.Redisson.create(Redisson.java:99)
        at org.redisson.spring.starter.RedissonAutoConfiguration.redisson(RedissonAutoConfiguration.java:164)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$29e2b633.CGLIB$redisson$1(<generated>)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$29e2b633$$FastClassBySpringCGLIB$$8adfa544.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at org.redisson.spring.starter.RedissonAutoConfiguration$$EnhancerBySpringCGLIB$$29e2b633.redisson(<generated>)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 96 common frames omitted

```

**Comment by yury-s** [comment]
Closing as it is not a Playwright bug. Please follow the bug template if you think otherwise.
