### ISSUE TITLE
[Question] "Failed to find playwright-cli " exception for execution via "java -jar " command

### ISSUE THREAD

**Issue by ercanku** [microsoft/playwright-java#183]
After packaging the example project which is https://github.com/microsoft/playwright-java/tree/master/examples, it is not possible to execute via java -jar . It cause the exception mentioned below: 

```
Caused by: java.lang.RuntimeException: Failed to find playwright-cli
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:46) ~[driver-0.171.0.jar!/:na]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:38) ~[playwright-0.171.0.jar!/:na]
	at com.microsoft.playwright.Playwright.create(Playwright.java:25) ~[playwright-0.171.0.jar!/:na]
```

**Comment by codeboyzhou** [comment]
@ercanku Hi, the code of module `example` can't be executed directly by `java -jar`, because `playwright-java` need to depend on the driver (`playwright-cli`), so maybe you need to create a new maven project and according to the `README.md`.

1. Add the dependency to your maven `pom.xml` (Now its version should be 0.172.3 in maven central repository).
```
<dependency>
  <groupId>com.microsoft.playwright</groupId>
  <artifactId>playwright</artifactId>
  <version>0.171.0</version>
</dependency>
```
2. Copy the code from module `example` or `README.md` to your project.
3. Run or Debug your project, it will work if there is no other issues.

Please notice that it will download and install browsers if you are running `playwright-java` at the first time.

**Comment by ercanku** [comment]
Hi @codeboyzhou, 
It works with `mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot` which is mentioned on examples but it is not appropriate for production environments. It should be in a packaged form. So, do you have any advice or approach for that?

P.s.: I have installed playwright-cli separately and passed the path as a property like  `-Dplaywright.cli.dir` but still thown the same exception.

**Comment by yury-s** [comment]
> It works with `mvn compile exec:java -Dexec.mainClass=org.example.PageScreenshot` which is mentioned on examples but it is not appropriate for running on a server. It should be in a packaged form. So, do you have any advice or approach for that?
> 
You can either add all required dependencies to the classpath when running from jar or you can use Maven to package all dependencies in a single jar. There is plenty of ways to do it with Maven, you can look at https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven for some pointers.

> P.s.: I have installed playwright-cli separately and passed the path as a property like `-Dplaywright.cli.dir` but still thown the same exception.

That should work as long as `playwright.cli.dir` contains `playwright-cli` executable. Note that in this case you'll have to add jars produced by `driver` and `playwright` modules to the classpath. What's the command line you use to launch your test?

**Comment by ercanku** [comment]
Hi @yury-s ,
It is not a missing dependency problem. I have inspected the code in detail. 

During the playwright-cli installation, it tries to list the files under `driver-bundle-0.171.0.jar!/driver` path via `Files.list(Paths.get(uri))` on **DriverJar -> extractDriverToTempDir** . If you run the project from an IDE or via `mvn compile exec:java ` it works fine because the driver bundle path is a default .m2 folder related path which is normal file system path. 
But if you run from a jar file, that path is nested jar path and `Files.list(Paths.get(uri))` does not work for it. And it throws `java.nio.file.NotDirectoryException`



```
Caused by: java.lang.RuntimeException: Failed to find playwright-cli
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:46) ~[driver-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:38) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.Playwright.create(Playwright.java:25) ~[playwright-0.171.0.jar!/:na]
        at com.prisync.apps.browser.BrowserFactory.create(BrowserFactory.java:15) ~[classes!/:1.0-SNAPSHOT]
        at com.prisync.apps.Crawler.<init>(Crawler.java:26) ~[classes!/:1.0-SNAPSHOT]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_241]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        ... 29 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_241]
        at com.microsoft.playwright.impl.Driver.createDriver(Driver.java:61) ~[driver-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:44) ~[driver-0.171.0.jar!/:na]
        ... 38 common frames omitted
**Caused by: java.nio.file.NotDirectoryException: /BOOT-INF/lib/driver-bundle-0.171.0.jar!/driver/mac
        at com.sun.nio.zipfs.ZipDirectoryStream.<init>(ZipDirectoryStream.java:73) ~[zipfs.jar:1.8.0_241]
        at com.sun.nio.zipfs.ZipPath.newDirectoryStream(ZipPath.java:651) ~[zipfs.jar:1.8.0_241]
        at com.sun.nio.zipfs.ZipFileSystemProvider.newDirectoryStream(ZipFileSystemProvider.java:262) ~[zipfs.jar:1.8.0_241]
        at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[na:1.8.0_241]
        at java.nio.file.Files.list(Files.java:3451) ~[na:1.8.0_241]
        at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:53) ~[driver-bundle-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:32) ~[driver-bundle-0.171.0.jar!/:na]
        ... 44 common frames omitted**
```

**Comment by yury-s** [comment]
> During the playwright-cli installation, it tries to list the files under `driver-bundle-0.171.0.jar!/driver` path

Yes, this is expected. The [examples](https://github.com/microsoft/playwright-java/tree/master/examples) project does the same. Local path will only be used if you build playwright locally.

How do you build the jar file you are trying to launch? Can you share you Maven project (or whatever build system you use) and the command line you use to launch it?

For now you can use `playwright.cli.dir` as a workaround. Did you manage to download playwright-cli? [This script](https://github.com/microsoft/playwright-java/blob/master/scripts/download_driver_for_all_platforms.sh) is used by our build to download the driver.

**Comment by ercanku** [comment]
I realized that the problem is Spring Boot related. It is about Spring boot packaging.

 java -jar works fine with the example mentioned the playwright-java/example repository.

I have created an Spring Boot Playwright example application in here:
`https://github.com/ercanku/spring-boot-playwright`

Run commands:

```
 mvn clean package 
 java -jar target/spring-boot-playwright-1.0-SNAPSHOT.jar
```




The exception is :

```2021-01-07 13:31:43.152 ERROR 67895 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at com.example.app.PlaywrightSpringApplication.main(PlaywrightSpringApplication.java:11) [classes!/:1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) [spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
Caused by: java.lang.RuntimeException: Failed to find playwright-cli
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:46) ~[driver-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:38) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.Playwright.create(Playwright.java:25) ~[playwright-0.171.0.jar!/:na]
        at com.example.app.PageScreenshot.fetch(PageScreenshot.java:15) ~[classes!/:1.0-SNAPSHOT]
        at com.example.app.PlaywrightSpringApplication.run(PlaywrightSpringApplication.java:17) [classes!/:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        ... 13 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_241]
        at com.microsoft.playwright.impl.Driver.createDriver(Driver.java:61) ~[driver-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:44) ~[driver-0.171.0.jar!/:na]
        ... 18 common frames omitted
Caused by: java.nio.file.NotDirectoryException: /BOOT-INF/lib/driver-bundle-0.171.0.jar!/driver/mac
        at com.sun.nio.zipfs.ZipDirectoryStream.<init>(ZipDirectoryStream.java:73) ~[zipfs.jar:1.8.0_241]
        at com.sun.nio.zipfs.ZipPath.newDirectoryStream(ZipPath.java:651) ~[zipfs.jar:1.8.0_241]
        at com.sun.nio.zipfs.ZipFileSystemProvider.newDirectoryStream(ZipFileSystemProvider.java:262) ~[zipfs.jar:1.8.0_241]
        at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[na:1.8.0_241]
        at java.nio.file.Files.list(Files.java:3451) ~[na:1.8.0_241]
        at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:53) ~[driver-bundle-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.DriverJar.<init>(DriverJar.java:32) ~[driver-bundle-0.171.0.jar!/:na]
        ... 24 common frames omitted
```

And then I used the script you mentioned, and download the driver and install cli with `"npm install playwright"`

Run with driver parameter :

`java -Dplaywright.cli.dir=/pw-java/driver/linux  -jar spring-boot-playwright-1.0-SNAPSHOT.jar `

And final exception is : 

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at com.example.app.PlaywrightSpringApplication.main(PlaywrightSpringApplication.java:11) ~[classes!/:1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:466) ~[spring-boot-playwright-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
Caused by: com.microsoft.playwright.PlaywrightException: Error: Failed to launch firefox because executable doesn't exist at /root/.cache/ms-playwright/firefox-1224/firefox/firefox
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
        at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:50) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.ChannelOwner.lambda$toDeferred$0(ChannelOwner.java:97) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:77) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:80) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:39) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:28) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.BrowserType.launch(BrowserType.java:594) ~[playwright-0.171.0.jar!/:na]
        at com.example.app.PageScreenshot.fetch(PageScreenshot.java:24) ~[classes!/:1.0-SNAPSHOT]
        at com.example.app.PlaywrightSpringApplication.run(PlaywrightSpringApplication.java:17) ~[classes!/:1.0-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        ... 13 common frames omitted
Caused by: com.microsoft.playwright.impl.ServerException: Error: Failed to launch firefox because executable doesn't exist at /root/.cache/ms-playwright/firefox-1224/firefox/firefox
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
        at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:146) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:130) ~[playwright-0.171.0.jar!/:na]
        at com.microsoft.playwright.impl.ChannelOwner.lambda$toDeferred$0(ChannelOwner.java:95) ~[playwright-0.171.0.jar!/:na]
        ... 21 common frames omitted
```

It still cant find Firefox. It looks at `/root/.cache/ms-playwright/firefox-1224/firefox/firefox` path. But the cli  install firefox on 
`/root/.cache/ms-playwright/firefox-1221`. Directory suffix is 1221, not 1224. 

So, how is this suffix managed among cli, driver and library?

**Comment by ercanku** [comment]
By the way, when I renamed the directory as firefox-1224, it works. But I think it is not a good way to fix it.

**Comment by ercanku** [comment]
Last update, I changed CLI_VERSION to 0.170.0 when I run driver download script. And now, everything is fine. 👍

**Comment by ivanli1990** [comment]
> @ercanku Hi, the code of module `example` can't be executed directly by `java -jar`, because `playwright-java` need to depend on the driver `playwright-cli`, so maybe you can create a new maven project and according to the `README.md`.
> 
> 1. Add the dependency to your maven `pom.xml`.
> 
> ```
> <dependency>
>   <groupId>com.microsoft.playwright</groupId>
>   <artifactId>playwright</artifactId>
>   <version>0.171.0</version>
> </dependency>
> ```
> 
> 1. Copy the code from module `example` or `README.md` to your project.
> 2. Run or Debug your project, it will work if there is no other issues.
> 
> Please notice that it will download and install browsers if you are running `playwright-java` at the first time.

Hi @codeboyzhou, I meet this issue too.
So What you mean is executing `mvn compile exec:java -Dexec.mainClass=myClass` firstly, and then run the project?
I did steps above, and downloaded chromium in `/Users/ivanli/Library/Caches/ms-playwright/chromium-833159` but firefox timeout as below:
```
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
Downloading chromium v833159 - 96.9 Mb [====================] 100% 0.0s 
chromium v833159 downloaded to /Users/ivanli/Library/Caches/ms-playwright/chromium-833159
Downloading firefox v1221 - 74.4 Mb [=                   ] 3% 7523.1s [WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to find playwright-cli
```
And then, I rerun the project(ps, I just need chromium only), cause the exception below:
```
(node:64882) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at /snapshot/playwright-cli/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/snapshot/playwright-cli/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:168:5)
(node:64882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



java.lang.StackOverflowError
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383)
	at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378)
```
So my questions as below:
1. What are the steps to correctly access for using playwright-java?
2. Why playwright-java reinstall chromium(v833159) but not use local installed chromium(v827102 which installed by playwright-python early)?
3. How to install the specified browser(chromium) only, not all browsers(chromium, fireforx, webKit)
