### ISSUE TITLE
[Question] Failed to launch chromium because executable doesn't exist

### ISSUE THREAD

**Issue by okohll** [microsoft/playwright-java#346]
Hi, I have an issue launching the Chromium browser, on Ubuntu 20 LTS. The error only occurs one one of three Ubuntu 20 servers, so hopefully it is a configuration issue, but the error message seems like it's maybe an overhang from the node version.

This is being run from within a Tomcat 9 Java servlet application. The Playwright version is v1.9.1-alpha-0.

My code is

```
private static void generatePdfPlaywright(File htmlSourceFile, File pdfToGenerate) {
    try (Playwright playwright = Playwright.create();
         Browser browser = playwright.chromium().launch();
         BrowserContext browserContext = browser.newContext(new Browser.NewContextOptions().setViewportSize(1280, 800));
         Page page = browserContext.newPage()) {
        page.navigate("file://" + htmlSourceFile.getAbsolutePath());
        Page.PdfOptions pdfOptions = new Page.PdfOptions().setFormat("A4").setPath(pdfToGenerate.toPath());
        page.pdf(pdfOptions);
    }
}

```

and the stack trace is
```
 -  - com.microsoft.playwright.impl.DriverException: Error {
  message='Failed to launch chromium because executable doesn't exist at /.cache/ms-playwright/chromium-854489/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
  name='Error
  stack='Error: Failed to launch chromium because executable doesn't exist at /.cache/ms-playwright/chromium-854489/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
    at Chromium._launchProcess (/tmp/playwright-java-5158158360901142005/package/lib/server/browserType.js:173:19)
    at async Chromium._innerLaunch (/tmp/playwright-java-5158158360901142005/package/lib/server/browserType.js:110:62)
    at async ProgressController.run (/tmp/playwright-java-5158158360901142005/package/lib/server/progress.js:79:28)
    at async Chromium.launch (/tmp/playwright-java-5158158360901142005/package/lib/server/browserType.js:78:25)
    at async BrowserTypeDispatcher.launch (/tmp/playwright-java-5158158360901142005/package/lib/dispatchers/browserTypeDispatcher.js:30:25)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-5158158360901142005/package/lib/dispatchers/dispatcher.js:178:28)
}
 - Stack trace:
   com.microsoft.playwright.impl.Connection.dispatch(Connection.java:209)
   com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:189)
   com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:86)
   com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:96)
   com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:79)
   com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:49)
   com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:41)
   com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
   com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:41)
   com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:34)
   com.microsoft.playwright.BrowserType.launch(BrowserType.java:582)
   com.gtwm.pb.background.SubscriptionSender.generatePdfPlaywright(SubscriptionSender.java:161)
   com.gtwm.pb.background.SubscriptionSender.sendReportSubscriptions(SubscriptionSender.java:97)
   com.gtwm.pb.background.SubscriptionSender.run(SubscriptionSender.java:55)
   com.gtwm.pb.servlets.ServletDataMethods.sendReportSubscription(ServletDataMethods.java:566)
   com.gtwm.pb.servlets.AppController.carryOutAppActions(AppController.java:617)
   com.gtwm.pb.servlets.AppController.handleRequest(AppController.java:878)
   org.apache.velocity.tools.view.VelocityViewServlet.doRequest(VelocityViewServlet.java:236)
 - Stack trace:
   com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
   com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:88)
   com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:96)
   com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:79)
   com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:49)
   com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:41)
   com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
   com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:41)
   com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:34)
   com.microsoft.playwright.BrowserType.launch(BrowserType.java:582)
   com.gtwm.pb.background.SubscriptionSender.generatePdfPlaywright(SubscriptionSender.java:161)
```

Can you think of any possible causes?

**Comment by yury-s** [comment]
Playwright downloads browsers on start into `$HOME/.cache/ms-playwright` directory. If it fails to do so Playwright.create should throw but it looks like it doesn't in your case and you code proceeds to launching Chromium. The location `/.cache/ms-playwright/chromium-854489/chrome-linux/chrome` looks wrong unless your home directory is `/`. Can you check what is the value of `System.getenv("HOME")` inside generatePdfPlaywright?

**Comment by okohll** [comment]
Yuri, thanks, that is the issue. The tomcat user which is running the app doesn't have a home directory, but if I create one for it with

```mkdir /home/tomcat
chown tomcat:tomcat /home/tomcat
```
and assign it in /etc/passwd

that fixes it.

Without that, `System.getenv("HOME")` outputs null.
