### ISSUE TITLE
[Question] Cannot take a screenshot while page is navigating

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#375]
I took a screenshot after page.waitForNavigation(), but it failed and report this.
`com.microsoft.playwright.PlaywrightException: Error {
  message='Cannot take a screenshot while page is navigating
  name='Error
  stack='Error: Cannot take a screenshot while page is navigating
    at rewriteError (C:\Users\LWX884~1\AppData\Local\Temp\playwright-java-5730335139594947967\package\lib\server\chromium\crExecutionContext.js:115:15)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:434:9)
    at async CRExecutionContext.rawEvaluate (C:\Users\LWX884~1\AppData\Local\Temp\playwright-java-5730335139594947967\package\lib\server\chromium\crExecutionContext.js:49:60)
    at async evaluateExpression (C:\Users\LWX884~1\AppData\Local\Temp\playwright-java-5730335139594947967\package\lib\server\javascript.js:149:27)
    at async Screenshotter._originalViewportSize (C:\Users\LWX884~1\AppData\Local\Temp\playwright-java-5730335139594947967\package\lib\server\screenshotter.js:34:28)
    at async C:\Users\LWX884~1\AppData\Local\Temp\playwright-java-5730335139594947967\package\lib\server\screenshotter.js:55:60
}`

The final action is 
```java
page.waitForNavigation(() -> {page.press("[placeholder=\"password\"]", "Enter");});
page.screenshot(new Page.ScreenshotOptions().setFullPage(true).setPath(xxx));
```
I wonder why there is no auto-waiting before the screenshot action.

**Comment by yury-s** [comment]
The problem is that your scenario is inherently racy. You already wait for the first navigation, if we did it internally in `page.screenshot` it wouldn't change much as another navigation would start while the screenshot is being taken. What we could do is automatically retry such failures internally but this has another issue that the method would potentially hang if the page is in an infinite redirect loop. You can already achieve same result on the client end:

```java
page.waitForNavigation(() -> {page.press("[placeholder=\"password\"]", "Enter");});
int maxAttempts = 100;
for (int i = 0; i < maxAttempts; i++) {
  try {
    page.screenshot(new Page.ScreenshotOptions().setFullPage(true).setPath(xxx));
    break;
  } catch (PlaywrightException e) {
    continue;
  }
}
```
Another alternative would be to just return a blank image if screenshot failed because of ongoing navigation, this would be quite accurate result because the page does actually go through the blank state during navigation. Would that work for you?
