### ISSUE TITLE
[Question] BrowserType.LaunchOptions.setChannel fails unless BrowserChannel.CHROME is provided

### ISSUE THREAD

**Issue by moikeygraham** [microsoft/playwright-java#391]
**Context:**
- Playwright Version: 1.10.0
- Operating System: macOS Catalina
- Java version: 11

**Describe the bug**
Providing a channel with anything other than `BrowserChannel.CHROME` fails with `Chromium distribution was not found: xxxx`

```java
Playwright.create().chromium().launch(new BrowserType.LaunchOptions().setChannel(BrowserType.MSEDGE));
```

```
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Chromium distribution was not found: msedge
  name='Error
  stack='Error: Chromium distribution was not found: msedge
    at Object.findChromiumChannel (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/chromium/findChromiumChannel.js:97:11)
    at Chromium.executablePath (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/chromium/chromium.js:44:42)
    at Chromium._launchProcess (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/browserType.js:166:51)
    at async Chromium._innerLaunch (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/browserType.js:110:62)
    at async ProgressController.run (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/progress.js:79:28)
    at async Chromium.launch (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/server/browserType.js:78:25)
    at async BrowserTypeDispatcher.launch (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/dispatchers/browserTypeDispatcher.js:30:25)
    at async DispatcherConnection.dispatch (/private/var/folders/53/yy7ptbd161569bs96h4d9g540000gp/T/playwright-java-5414780740324138589/package/lib/dispatchers/dispatcher.js:181:28)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:209)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:189)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:86)
	... 81 common frames omitted
```

**Comment by yury-s** [comment]
You have to install MS Edge manually. [Here](https://github.com/microsoft/playwright/blob/d9546fd09867e2455d9a4a8722a7a5563b146ae5/src/server/chromium/findChromiumChannel.ts#L26) is the code that determines browser path depending on the channel. For 'msedge' please make sure it is installed, I believe `/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge` just does not exist.
