### ISSUE TITLE
[Bug] Wait for file chooser event is not working

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright-java#412]
I am trying the following
```
        Playwright playwright = Playwright.create();
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                .setHeadless(false));
        BrowserContext context = browser.newContext();
        Page page = context.newPage();
        page.navigate("some url");

        page.type("//input[@name='email']", "username");
        page.type("//input[@name='password']", "password");
        page.click("//button[@type='submit']");

        FileChooser fileChooser = page.waitForFileChooser(() -> {
            page.click("#file");
        });

        fileChooser.setFiles(Path.of("./upload_findings.csv"));
```

File chooser is opened but `Exception in thread "main" com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded` is thrown at `page.waitForFileChooser`. Timeout is enough, it waits but throws in the end.

I tried the same with js playwright and it is working fine.

**Comment by Kremliovskyi** [comment]
@yury-s 
Click succeeded, I mentioned this in description - file chooser appears but the wait is not resolved. The same is working in playwright for js (and with same selector). Here is debug log 
[filechooser.log](https://github.com/microsoft/playwright-java/files/6404292/filechooser.log)
Web site is available only from private netwrok, I can not share it, sorry.

**Comment by yury-s** [comment]
> Is there something else I can share?

Could you collect chromium logs by launching playwright with `DEBUG=pw:protocol`? it should tell us more about what happens in the browser, from the api log it seems that filechooser has not been opened.

Can you also share corresponding js code that works (want to double check if there are any subtle differences)?

**Comment by Kremliovskyi** [comment]
@yury-s Here are logs - 
[filechooser-protocol.log](https://github.com/microsoft/playwright-java/files/6407543/filechooser-protocol.log)
This part appeared together with error - I have rechecked
```
2021-04-30T19:03:44.026Z pw:protocol SEND ► {"id":247,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":false},"sessionId":"F4E8B0002CEEF3F3A72D59C0D5ADE3DF"}
2021-04-30T19:03:44.027Z pw:protocol SEND ► {"id":248,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":false},"sessionId":"37685066EFAFC83F8505E437A61F027E"}
2021-04-30T19:03:44.028Z pw:protocol ◀ RECV {"id":248,"result":{},"sessionId":"37685066EFAFC83F8505E437A61F027E"}
2021-04-30T19:03:44.028Z pw:protocol ◀ RECV {"id":247,"result":{},"sessionId":"F4E8B0002CEEF3F3A72D59C0D5ADE3DF"}
2021-04-30T19:03:44.029Z pw:protocol SEND ► {"id":249,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":false},"sessionId":"F4E8B0002CEEF3F3A72D59C0D5ADE3DF"}
2021-04-30T19:03:44.029Z pw:protocol SEND ► {"id":250,"method":"Page.setInterceptFileChooserDialog","params":{"enabled":false},"sessionId":"37685066EFAFC83F8505E437A61F027E"}
2021-04-30T19:03:44.030Z pw:protocol ◀ RECV {"id":250,"result":{},"sessionId":"37685066EFAFC83F8505E437A61F027E"}
2021-04-30T19:03:44.031Z pw:protocol ◀ RECV {"id":249,"result":{},"sessionId":"F4E8B0002CEEF3F3A72D59C0D5ADE3DF"}
Exception in thread "main" com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded
	at com.microsoft.playwright.impl.WaitableTimeout.get(WaitableTimeout.java:41)
	at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:44)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:88)
	at com.microsoft.playwright.impl.PageImpl.waitForEventWithTimeout(PageImpl.java:467)
	at com.microsoft.playwright.impl.PageImpl.waitForFileChooser(PageImpl.java:484)
	at com.microsoft.playwright.Page.waitForFileChooser(Page.java:3911)
	at playWrightTest.UploadFindingsTest.main(UploadFindingsTest.java:21)
```

**Comment by Kremliovskyi** [comment]
@yury-s 
This is js example:
```
    async #uploadFile() {
        const [fileChooser] = await Promise.all([
            this.page.waitForEvent('filechooser'),
            this.page.click(this.elements.csvInput)
        ]);
        await fileChooser.setFiles('./resources/upload_findings.csv');
        await this.page.click(this.elements.uploadButton);
    }
```
`csvInput: "#file",` selector is the same

Here is js protocol log
[filechooser-protocol-js.log](https://github.com/microsoft/playwright-java/files/6407588/filechooser-protocol-js.log)

**Comment by yury-s** [comment]
Ok, it's clear from the log that 'Page.fileChooserOpened' is not fired in case of Java even though you click at the same point on apparently the same element. Looks like there is a race condition in the page. Can you try running it with inspector (set `PWDEBUG=1` in the environment) and see whether the cursor points to correct element.

> This part appeared together with error - I have rechecked

In java log this happens after 30s timeout when we remove filechooser listener, this is expected.

**Comment by Kremliovskyi** [comment]
Inspector has appeared it looked like this 
![debugger](https://user-images.githubusercontent.com/12884831/116780351-d7ed7300-aa84-11eb-9729-e0133b871e63.png)
When I hovered over click event it highlighted input field correctly, as you can see file chooser is opened

**Comment by yury-s** [comment]
This is very strange, the filechooser is there but not reported by the browser over CDP.

@Kremliovskyi  Can I ask you to run node version with `PWDEBUG=1` too? The reason I'm interested in that is that inspector would introduce some artificial delays which may reveal the same issue in nodejs version.

**Comment by Kremliovskyi** [comment]
@yury-s I have played more with it. I have added hardcoded wait 
```java
        page.waitForTimeout(20000d);
        FileChooser fileChooser = page.waitForFileChooser(() -> {
            page.click("#file");
        });
```
After I added it filechooser does not appear on the site but wait is resolved and FileChooser instance is returned
![image](https://user-images.githubusercontent.com/12884831/117467239-2bb3fc80-af5c-11eb-8c82-6779633415be.png)

When it comes to set files method `fileChooser.setFiles(Path.of("src/main/java/playWrightTest/upload_findings.csv"));`
 I got this
```
Exception in thread "main" java.util.ServiceConfigurationError: java.nio.file.spi.FileTypeDetector: Provider org.openrdf.rio.helpers.RioFileTypeDetector not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at java.base/java.nio.file.Files$FileTypeDetectors$2.run(Files.java:1584)
	at java.base/java.nio.file.Files$FileTypeDetectors$2.run(Files.java:1579)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.nio.file.Files$FileTypeDetectors.loadInstalledDetectors(Files.java:1579)
	at java.base/java.nio.file.Files$FileTypeDetectors.<clinit>(Files.java:1565)
	at java.base/java.nio.file.Files.probeContentType(Files.java:1642)
	at com.microsoft.playwright.impl.Utils.mimeType(Utils.java:107)
	at com.microsoft.playwright.impl.Utils.toFilePayloads(Utils.java:126)
	at com.microsoft.playwright.impl.FileChooserImpl.setFiles(FileChooserImpl.java:61)
	at com.microsoft.playwright.impl.FileChooserImpl.setFiles(FileChooserImpl.java:56)
	at com.microsoft.playwright.FileChooser.setFiles(FileChooser.java:71)
	at playWrightTest.UploadFindingsTest.main(UploadFindingsTest.java:26)
```

I have rechecked that this is true
```java
System.out.println(Path.of("src/main/java/playWrightTest/upload_findings.csv")
                .toFile().exists());
```

**Comment by Kremliovskyi** [comment]
@yury-s This nodejs PWDEBUG=1
![Screenshot_4](https://user-images.githubusercontent.com/12884831/117468744-aa5d6980-af5d-11eb-97f5-df98951f7ce1.png)

Here is this wait for file chooser event while java playwright does not have it.

**Comment by Kremliovskyi** [comment]
@yury-s Here is the log 
[successful.log](https://github.com/microsoft/playwright-java/files/6443596/successful.log)

`java.nio.file.Files.probeContentType(Path.of("src/main/java/playWrightTest/upload_findings.csv"))` yes this fails with the same error but the file is not corrupted or anything. It is correctly opened by any editor, web site parses it correctly, etc.

**Comment by Kremliovskyi** [comment]
@yury-s I have removed hardcoded wait and waitForFileChooser also. The file chooser is opened just fine.

**Comment by Kremliovskyi** [comment]
@yury-s Here is the log 
[moreLogs.log](https://github.com/microsoft/playwright-java/files/6445675/moreLogs.log)

**Comment by Kremliovskyi** [comment]
@yury-s It passes. It would be convenient to have all required waits inside `input.click();` like what `page.waitForSelector("#file");` does.

**Comment by yury-s** [comment]
> @yury-s It passes. It would be convenient to have all required waits inside `input.click();`

It does all the same waits as `page.click()` except for waiting until the selector is resolved to an element as the element is already provided in this case.

**Comment by Kremliovskyi** [comment]
@yury-s or just use nodejs version of playwright ;)

**Comment by yury-s** [comment]
> @yury-s or just use nodejs version of playwright ;)

It should make no difference, the underlying driver and browser code is the same. The timing is slightly different in java because of the synchronous nature of the client side API. Some race conditions are more likely to occur in one language than the other but if it occurs in one there is a chance you'll eventually face it in the other too.

**Comment by corneliusroemer** [comment]
I'm hitting this issue as well, also using React and about 1 in 5 times the fileChooser event doesn't fire.
