### ISSUE TITLE
[Question] new channels api is failing

### ISSUE THREAD

**Issue by qwpnqjucz** [microsoft/playwright-java#421]
I tried running the new channels api to try different versions of chrome and, aside from `BrowserChannel.CHROME`, each one fails with:

```
com.microsoft.playwright.PlaywrightException: Error {
  message='Chromium distribution 'chrome-dev' is not supported on win32
  name='Error
  stack='Error: Chromium distribution 'chrome-dev' is not supported on win32
    at Object.findChromiumChannel (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\chromium\findChromiumChannel.js:94:15)
    at Chromium.executablePath (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\chromium\chromium.js:44:42)
    at Chromium._launchProcess (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\browserType.js:166:51)
    at async Chromium._innerLaunch (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\browserType.js:110:62)
    at async ProgressController.run (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\progress.js:79:28)
    at async Chromium.launch (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\server\browserType.js:78:25)
    at async BrowserTypeDispatcher.launch (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\dispatchers\browserTypeDispatcher.js:30:25)
    at async DispatcherConnection.dispatch (C:\Users\xxxxxxxxxxxxx\AppData\Local\Temp\2\playwright-java-71678648889713603\package\lib\dispatchers\dispatcher.js:181:28)
}
```

**Comment by yury-s** [comment]
The error message is misleading but the problem is that you only have Chrome stable installed on your system. You need to install Chrome Dev manually on the system.

**Comment by qwpnqjucz** [comment]
I thought playwright downloaded browsers for you?


________________________________

**Comment by yury-s** [comment]
It only downloads most recent (tip-of-tree) versions currently which is enough for most clients.If you want to test against a particular official release that includes proprietary stuff (Chrome, Edge, Opera etc) you have to install it yourself.
