### ISSUE TITLE
[BUG] Protocol error (Page.insertText): error in channel "content::page" When fill Input

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright-java#465]
The same script can run normally on Chromium. On Firefox, a message is displayed indicating that an element is invisible and an exception is thrown.
The following are the captured exception contents：
```
'Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:767:32
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
waiting for selector "[placeholder="please input alarm name"]"
  selector resolved to visible <input ng-trim="true" maxlength="256" ng-model="value" …/>
elementHandle.fill("fastunitcmc_test")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
  name='Error
  stack='Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:767:32
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
waiting for selector "[placeholder="please input alarm name"]"
  selector resolved to visible <input ng-trim="true" maxlength="256" ng-model="value" …/>
elementHandle.fill("fastunitcmc_test")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.Error
    at C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\firefox\ffConnection.js:149:63
    at new Promise (<anonymous>)
    at FFSession.send (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\firefox\ffConnection.js:148:16)
    at RawKeyboardImpl.sendText (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\firefox\ffInput.js:88:28)
    at Keyboard.insertText (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\input.js:78:25)
    at C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\dom.js:457:47
    at async FrameManager.waitForSignalsCreatedBy (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\frames.js:109:24)
    at async Frame._retryWithProgressIfNotConnected (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\frames.js:781:28)
    at async C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\frames.js:817:35
    at async ProgressController.run (C:\Users\ADMINI~1\AppData\Local\Temp\playwright-java-532090625998089968\package\lib\server\progress.js:76:28)
})
```

**Comment by yury-s** [comment]
Can you share code snippet of the page with the input element where this is reproducible?

**Comment by mxschmitt** [comment]
Closed as part of the triage, please reopen / create a new issue with a reproducible if you still face the issue.

**Comment by Gaket** [comment]
I get this issue when I use Pycharm's REPL to be able to debug my tests. Clicks work well, but dispatching key vns - don't.
STR that work 100% for me on Firefox Nightly (90.0 (64-bit)):

1. Start a script
2. Interupt it in the middle with Ctrl+C
3. Repl gets back to console, everything seems to work but keyboard input

```
Protocol error (Page.dispatchKeyEvent): error in channel "content::page": exception while running method "dispatchKeyEvent" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.keydown] _dispatchKeyEvent@chrome://juggler/content/content/PageAgent.js:563:13
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
=========================== logs ===========================
waiting for selector "#licenceNumber"
  selector resolved to visible <input type="text" required="" maxlength="17" id="licen…/>
elementHandle.type("M03781670935126")
============================================================
```

```
Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:765:32
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
waiting for selector "#number"
  selector resolved to visible <input type="text" required="" maxlength="17" id="licen…/>
elementHandle.fill("data")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable
============================================================
````

**Comment by Gaket** [comment]
Oops, jsut noticed that it's a Java repo, sorry 🤦 
But may be you will find some similarities in behavior
