### ISSUE TITLE
[Feature] connectOverCDP gives: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by rlundy** [microsoft/playwright-java#496]
We're using Selenium Box (from Element34) as our browser host, and I'm trying to connect to it with Selenium.  (Selenium Box itself works fine; we already use it for hundreds of Selenium tests.)

We run our tests through a Jenkins job.  When I try to use `connectOverCDP` to get a browser from Selenium Box, I get the message below:

Is there a reason https isn't supported?  How difficult would it be to support?

```
com.microsoft.playwright.PlaywrightException: Error {
  message='Protocol "https:" not supported. Expected "http:"
  name='TypeError
  stack='TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:151:11)
    at request (http.js:46:10)
    at Object.get (http.js:50:15)
    at json (/tmp/playwright-java-3633253077079828231/package/lib/server/chromium/chromium.js:203:24)
    at new Promise (<anonymous>)
    at urlToWSEndpoint (/tmp/playwright-java-3633253077079828231/package/lib/server/chromium/chromium.js:202:24)
    at controller.run.timeoutSettings_1.TimeoutSettings.timeout.timeout.timeout (/tmp/playwright-java-3633253077079828231/package/lib/server/chromium/chromium.js:60:98)
    at async ProgressController.run (/tmp/playwright-java-3633253077079828231/package/lib/server/progress.js:76:28)
    at async BrowserTypeDispatcher.connectOverCDP (/tmp/playwright-java-3633253077079828231/package/lib/dispatchers/browserTypeDispatcher.js:38:25)
    at async DispatcherConnection.dispatch (/tmp/playwright-java-3633253077079828231/package/lib/dispatchers/dispatcher.js:232:22)
}
    at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
    at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:94)
    at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:102)
    at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:85)
    at com.microsoft.playwright.impl.BrowserTypeImpl.connectOverCDPImpl(BrowserTypeImpl.java:124)
    at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$connectOverCDP$4(BrowserTypeImpl.java:113)
    at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
    at com.microsoft.playwright.impl.BrowserTypeImpl.connectOverCDP(BrowserTypeImpl.java:113)
    at com.microsoft.playwright.BrowserType.connectOverCDP(BrowserType.java:665)
    at [our test]
```

**Comment by yury-s** [comment]
> Is there a reason https isn't supported? How difficult would it be to support?

Chromium itself exposes only http endpoint (it is a websocket to be more precise) which is what Playwright supports too. I don't see fundamental problems with adding support for https too. Who provides that https endpoint? Is it the same Chromium http connection proxied over https or is it something else? Is there a easy way for us to reproduce it?

**Comment by yury-s** [comment]
Also if the connection is established over https it should be a secure websocket (i.e. wss:// url) and someone have to translate from that to the Chrome's ws:// endpoint. What is the URL you pass to `BrowserType.connectOverCDP` ?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by unlikelyzero** [comment]
Re-opening with details here: https://github.com/microsoft/playwright/issues/8593

**Comment by rlundy** [comment]
`wss://` turned out to be what I needed to use.

I wonder if the error message could be clearer, though.

**Comment by yury-s** [comment]
https:// endpoint should also work, you were passing https://... url before and that should now work. Passing ws:// instead of wss:// would haved raised a different error.
