### ISSUE TITLE
[Bug] ElementHandle.hover() fails with IllegalStateException

### ISSUE THREAD

**Issue by dmoidl** [microsoft/playwright-java#508]
I've just stumbled upon a minor bug in the `ElementHandle.hover()` implementation. Using this default `hover()` method always results in this exception: 

```
java.lang.IllegalStateException: Not a JSON Object: null

	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at com.microsoft.playwright.impl.ElementHandleImpl.lambda$hover$13(ElementHandleImpl.java:213)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.ElementHandleImpl.hover(ElementHandleImpl.java:212)
	at com.microsoft.playwright.ElementHandle.hover(ElementHandle.java:1056)
        ...
```

Here is a [minimal reproducer](https://gist.github.com/dmoidl/96cdf07334481545ca8ad4857ed7e89d) showcasing the issue.

A quick look into the sources revealed that the problem is a forgotten `null` check in [this method](https://github.com/microsoft/playwright-java/blob/518f117fb0cbe35424f1644238ba8de18c9e290c/playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java#L210-L216). The `default void hover()` method calls this with `null` as the argument, making the implementation fail. All the other methods that take "options" (such as [click](https://github.com/microsoft/playwright-java/blob/518f117fb0cbe35424f1644238ba8de18c9e290c/playwright/src/main/java/com/microsoft/playwright/impl/ElementHandleImpl.java#L137-L143)) do seem to have a null check that prevents this.

I would send a PR, but don't really have the time for that at the moment 😇 So I'm at least creating this issue, maybe someone can fix it in the meantime...

**Comment by yury-s** [comment]
Thanks for reporting this! I prepared a fix.
