### ISSUE TITLE
[Bug]: strict page click option has no effect

### ISSUE THREAD

**Issue by metametadata** [microsoft/playwright-java#570]
### Playwright version

1.14.0

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### What happened? / Describe the bug

It looks like the new `strict` click mode has no effect:

```clj
(.click page "[value='Sign in']") (-> (Page$ClickOptions.)
                                      (.setStrict true))
```

Produces a timeout, unexpectedly:

```
com.microsoft.playwright.TimeoutError: Error {
                                         message='Timeout 5000ms exceeded.
                                       =========================== logs ===========================
                                       waiting for selector "[value='Sign in']"
                                         selector resolved to 2 elements. Proceeding with the first one.
                                         selector resolved to hidden <input type="Submit" value="Sign in" aria-label="submit…/>
                                       attempting click action
                                         waiting for element to be visible, enabled and stable
                                           element is not visible - waiting...
                                       ============================================================
                                         name='TimeoutError
                                         stack='TimeoutError: Timeout 5000ms exceeded.
                                       =========================== logs ===========================
                                       waiting for selector "[value='Sign in']"
                                         selector resolved to 2 elements. Proceeding with the first one.
                                         selector resolved to hidden <input type="Submit" value="Sign in" aria-label="submit…/>
                                       attempting click action
                                         waiting for element to be visible, enabled and stable
                                           element is not visible - waiting...
                                       ============================================================
                                           at ProgressController.run (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/progress.js:84:26)
                                           at Frame.click (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/frames.js:1015:23)
                                           at FrameDispatcher.click (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/dispatchers/frameDispatcher.js:159:30)
                                           at DispatcherConnection.dispatch (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/dispatchers/dispatcher.js:330:46)
                                       }

```

OTOH, using locator correctly detects strict mode violation:

```clj
(.click (.locator page "[value='Sign in']"))
```

Exception about 2 elements, as expected:

```
com.microsoft.playwright.impl.DriverException: Error {
                                                 message='Evaluation failed: strict mode violation: selector resolved to 2 elements.
                                               @debugger eval code line 3 > eval:20:31
                                               i@debugger eval code:3:37686
                                               pwExport</</pollRaf/<@debugger eval code:3:37773
                                               run@debugger eval code:3:38254
                                               @debugger eval code line 3 > eval:1:14
                                               evaluate@debugger eval code:3:1362
                                               @debugger eval code:1:44
                                               
                                               =========================== logs ===========================
                                               waiting for selector "[value='Sign in']"
                                                 strict mode violation: selector resolved to 2 elements.
                                               ============================================================
                                                 name='Error
                                                 stack='Error: Evaluation failed: strict mode violation: selector resolved to 2 elements.
                                               @debugger eval code line 3 > eval:20:31
                                               i@debugger eval code:3:37686
                                               pwExport</</pollRaf/<@debugger eval code:3:37773
                                               run@debugger eval code:3:38254
                                               @debugger eval code line 3 > eval:1:14
                                               evaluate@debugger eval code:3:1362
                                               @debugger eval code:1:44
                                               
                                               =========================== logs ===========================
                                               waiting for selector "[value='Sign in']"
                                                 strict mode violation: selector resolved to 2 elements.
                                               ============================================================
                                                   at checkException (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/firefox/ffExecutionContext.js:124:122)
                                                   at FFExecutionContext.evaluateWithArguments (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/firefox/ffExecutionContext.js:90:5)
                                                   at runNextTicks (internal/process/task_queues.js:62:5)
                                                   at processImmediate (internal/timers.js:434:9)
                                                   at async evaluateExpression (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/javascript.js:230:12)
                                                   at async InjectedScriptPollHandler.finishHandle (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/dom.js:910:22)
                                                   at async RerunnableTask.rerun (/private/var/folders/6g/9k9wc34n0hv_cn_1sq78xfdc0000gn/T/playwright-java-14912358379390524144/package/lib/server/frames.js:1420:73)
```

**Comment by metametadata** [comment]
I've put the bracket at incorrect place, it should be `(.click page "[value='Sign in']" (-> (Page$ClickOptions.) (.setStrict true)))` 🤦 Closing.
