### ISSUE TITLE
[BUG] Crash with "Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object"

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright-java#590]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: Playwright-Java
- Browser: Chromium
- Extra: Headed mode, with JVM debugger attached (started JUnit test from IntelliJ)

**Describe the bug**

Playwright crashed unexpectedly with the following error (some sensitive information redacted).

This same test has been running before without problems. This one test run it suddenly crashed (no changes to the config were made).

```
com.microsoft.playwright.PlaywrightException: Error {
  message='Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
=========================== logs ===========================
waiting for selector "id=logonIdentifier"
============================================================
  name='Error
  stack='Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
=========================== logs ===========================
waiting for selector "id=logonIdentifier"
============================================================Error
    at C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crConnection.js:202:16
    at new Promise (<anonymous>)
    at CRSession.send (C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crConnection.js:198:12)
    at CRExecutionContext.evaluateWithArguments (C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crExecutionContext.js:87:28)
    at evaluateExpression (C:\....\playwright-java-8267272157076441524\package\lib\server\javascript.js:230:36)
    at async RerunnableTask.rerun (C:\....\playwright-java-8267272157076441524\package\lib\server\frames.js:1421:77)
}

	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:109)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.FrameImpl.fillImpl(FrameImpl.java:337)
	at com.microsoft.playwright.impl.PageImpl.lambda$fill$27(PageImpl.java:700)
	at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
	at com.microsoft.playwright.impl.PageImpl.fill(PageImpl.java:699)
	at com.microsoft.playwright.Page.fill(Page.java:2988)
        ....
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: com.microsoft.playwright.impl.DriverException: Error {
  message='Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
=========================== logs ===========================
waiting for selector "id=logonIdentifier"
============================================================
  name='Error
  stack='Protocol error (Runtime.callFunctionOn): Argument should belong to the same JavaScript world as target object
=========================== logs ===========================
waiting for selector "id=logonIdentifier"
============================================================Error
    at C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crConnection.js:202:16
    at new Promise (<anonymous>)
    at CRSession.send (C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crConnection.js:198:12)
    at CRExecutionContext.evaluateWithArguments (C:\....\playwright-java-8267272157076441524\package\lib\server\chromium\crExecutionContext.js:87:28)
    at evaluateExpression (C:\....\playwright-java-8267272157076441524\package\lib\server\javascript.js:230:36)
    at async RerunnableTask.rerun (C:\....\playwright-java-8267272157076441524\package\lib\server\frames.js:1421:77)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:232)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:212)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	... 44 more
```

The stack traces includes the Java stack, but the error seems to me to be in the Node.js code.

**Comment by yury-s** [comment]
Can you share the code snippet that triggers this exception?

**Comment by jhyot** [comment]
By the way, I cannot reproduce it, it has only happened once so far.

The code in question is inside a page object, here is the method that I'm calling:

```java
public ManagerPage login(String username, String password) {
    page.fill(USERNAME_SELECTOR, username);
    page.fill(PASSWORD_SELECTOR, password);

    page.waitForNavigation(() -> page.click("id=next"));
    page.waitForLoadState(LoadState.NETWORKIDLE);

    return new ManagerPage(page);
}
```
where `USERNAME_SELECTOR` is the constant `"id=logonIdentifier"`, so according to the error message, it fails here on the first line.

Prior to calling `login()`, there is a redirect navigation involved (a logout), that is the only special thing that I can think of.
This is the logout action, so would be immediately preceding the `login` method call: 
```java
public LoginPage logout() {
    page.waitForNavigation(() ->
        accountMenu.locator("button[role='menuitem']:has-text('power_settings_new')")
            .click()
    );

    return new LoginPage(page);
}
```

**Comment by jhyot** [comment]
Also the login page is the Microsoft Azure AD B2C standard "user flow" login page, and it is heavily scripted. I think almost the whole DOM is created by Javascript. You can ask your Microsoft colleagues for an example of the B2C login page if necessary :)

**Comment by yury-s** [comment]
Thanks for the detailed description, this is really helpful! What I think is happening is that logout action results in a chain of navigations and `page.waitForNavigation` will only wait for the first one. Most of the times when the execution gets to the line ` page.fill(USERNAME_SELECTOR, username);` all these navigations are done. Sometimes though when you call `page.fill` one of the remaining navigations happens which makes `page.fill` throw this weird error (basically internally page.fill implementation gets a handle of an object from  the page before navigation and then passes it to a function in the page after navigation). This is inherently racy behavior so no surprise it cannot be easily reproduced. I see two solutions to this:
1. Create LoginPage with a fresh page rather than reusing one that is a result of a long logout redirect chain that you do not control. This is what we recommend in general - run each test in a new BrowserContext with new pages for better state isolation. If you have a multistep test scenario (login -> logout-> login again etc) or you just want to reuse the page for some other reason it may not work for you.
2. Use [page.waitForURL](https://playwright.dev/java/docs/api/class-page#page-wait-for-url) to ensure that the page is already on the final login page rather than some intermediate one.

Does any of the options work for you?

**Comment by jhyot** [comment]
Thanks for the explanation.

We have indeed a multi-step test scenario, so suggestion 1 is not so practical. Suggestion 2 would work. Also waiting for network idle might work, and which I'm already using a few times elsewhere as a "middle-ground" between the auto-wait and a fixed sleep.

But could the error message be improved here, so that it becomes clearer?

**Comment by yury-s** [comment]
> Also waiting for network idle might work, and which I'm already using a few times elsewhere as a "middle-ground" between the auto-wait and a fixed sleep.

I'd discourage you from using networkidle if you have more deterministic way of knowing that the page reached expected URL (be it waitForUrl or another condition). Not only does networkidle introduce extra 2s delays to your tests it will also break if one of the intermediate pages takes longer to navigate or if the page starts sending new requests.

> But could the error message be improved here, so that the issue becomes clearer?

Definitely. We should either say something like 'callFunctionOn failed because page has navigated' or do the call in the new page.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by AlexWebDev01** [comment]
Accidentally received the same error. The problem is still the same - chain of redirections. Easy solution: use waitForNavigation(waitUntil: 'networkidle0').
