### ISSUE TITLE
[Bug]: com.microsoft.playwright.PlaywrightException: Failed to launch driver

### ISSUE THREAD

**Issue by stefan-reich** [microsoft/playwright-java#597]
### Playwright version

1.14.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Ubuntu 18, JDK 16. Playwright build: https://botcompany.de/files/info/1400501

### What happened? / Describe the bug

Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-4739256218250876673/playwright.sh": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:43)
	... 52 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)

### Code snippet to reproduce your bug

I simply called `Playwright.create()`.

This is happening in some context which includes my own classloaders (usually it works fine), so the issue might be laying somewhere in there?

Any way to further investigate here?

Live demo: https://monitor.gazelle.rocks/beaHTML/22
Java code: https://monitor.gazelle.rocks/javaSource?id=22

### Relevant log output

```shell
com.microsoft.playwright.PlaywrightException: Failed to launch driver
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:50)
	at com.microsoft.playwright.Playwright.create(Playwright.java:88)
	at com.microsoft.playwright.Playwright.create(Playwright.java:92)
Caused by: java.io.IOException: Cannot run program "/tmp/playwright-java-4739256218250876673/playwright.sh": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:43)
	... 52 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
```

**Comment by yury-s** [comment]
> This is happening in some context which includes my own classloaders (usually it works fine), so the issue might be laying somewhere in there?

Definitely somewhere around that. We extract the driver into a temp directory on start, looks like it didn't happen. Perhaps you didn't include driver-bundle properly (look at `DriverJar.extractDriverToTempDir`)?

**Comment by yury-s** [comment]
What is the reason you use custom class loader? We officially support loading playwright as Maven modules, trying to pack everything into a single jar may require some extra tweaks to the code.

**Comment by stefan-reich** [comment]
> What is the reason you use custom class loader? We officially support loading playwright as Maven modules, trying to pack everything into a single jar may require some extra tweaks to the code.

The reason is that I offer a website where you can just put Java source code (actually it's a Java extension) in a database and it will be compiled, linked & loaded permanently, including near-orthogonal persistence. Try that with Maven... :)

[Example in question using Playwright](https://monitor.gazelle.rocks/crud/BEAObject?selectObj=22#obj22) (under one of the arrows you can see the transpiled Java source).

**Comment by stefan-reich** [comment]
> > This is happening in some context which includes my own classloaders (usually it works fine), so the issue might be laying somewhere in there?
> 
> Definitely somewhere around that. We extract the driver into a temp directory on start, looks like it didn't happen. Perhaps you didn't include driver-bundle properly (look at `DriverJar.extractDriverToTempDir`)?

OK we're getting somewhere. In fact on the same machine, in the same JVM, Playwright is already loaded & running fine. So my mistake is probably just loading it a second time (what's the policy on that)?

I can make the Playwright jar "sticky" which is my term for loading it at most once per JVM (I have a module system that allows loading and unloading libraries, even multiple times at once, but some libraries don't like that). I think that should actually solve this seeing as it is already working somewhere in the JVM.

Sorry to bother, will fix :)

**Comment by yury-s** [comment]
> OK we're getting somewhere. In fact on the same machine, in the same JVM, Playwright is already loaded & running fine. So my mistake is probably just loading it a second time (what's the policy on that)?

It's hard to tell without knowing how exactly you loader works but in general as long as static fields are getting initialized the same way  as on first load it should be fine. More generally, loading playwright multiple times in isolated class loaders should work.

Closing this bug as you seem to have solved the problem.

**Comment by stefan-reich** [comment]
@yury-s I have actually fixed the problem now. It was indeed in my custom classloader which resolved classes properly, but not resources. Thank you again for your help!

**Comment by yury-s** [comment]
Cool, thanks for the update!
