### ISSUE TITLE
 Failed to create driver(unable to resolve this  issue, can anyone help on this, gave full strack trace as well)

### ISSUE THREAD

**Issue by pchapekar1989** [microsoft/playwright-java#630]
Exception in thread "main" java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39)
	at com.microsoft.playwright.Playwright.create(Playwright.java:92)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.practise.playwright.PlaywrightTest.FirstTest.main(FirstTest.java:9)
Caused by: java.io.IOException: Cannot run program "C:\Users\hp\AppData\Local\Temp\playwright-java-13159650593791064633\playwright.cmd": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:60)
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:39)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
	... 4 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:492)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 8 more

**Comment by yury-s** [comment]
As the error reads the file "C:\Users\hp\AppData\Local\Temp\playwright-java-13159650593791064633\playwright.cmd" is not there. On each run Playwright extracts the driver into a temp folder and launches from there. I looks like in you case the file was was removed from there before playwright got a chance to launch it. Could it be that some antivirus kicks in or you have not enough space on the disk? Can you pause the app when such exception is thrown and manually check if the specified path is there? (you need to pause as the temp files are deleted on playwright process exit)
