### ISSUE TITLE
[Question]Exception : com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed. Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set.

### ISSUE THREAD

**Issue by agaramudhala** [microsoft/playwright-java#635]
Hi Team, 

Getting the below exception . 

com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed. 
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set. i'm running the test in  playwright docker img via jenkins.

**Comment by agaramudhala** [comment]
Running with **_DEBUG=pw:protocol_**, got the exceptions details.

Exception in thread "RMI TCP Connection(idle)" java.lang.NoSuchFieldError: instrumentedPeer
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:831)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Exception in thread "RMI TCP Connection(idle)" java.lang.NoSuchFieldError: instrumentedPeer
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:831)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Exception in thread "RMI TCP Connection(idle)" java.lang.NoSuchFieldError: instrumentedPeer
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:831)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Exception in thread "RMI TCP Connection(idle)" java.lang.NoSuchFieldError: instrumentedPeer
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:831)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Exception in thread "RMI TCP Connection(idle)" java.lang.NoSuchFieldError: instrumentedPeer
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:831)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)

**Comment by yury-s** [comment]
The stack trace doesn't contain anything about Playwright, it seems to be from a client end that does remote-method-invocation. Can you collect trace/logs on the server?

**Comment by agaramudhala** [comment]
I'm running tests on playwright docker container via Jenkins. Container already has chromium along with Java and maven!!

**Comment by yury-s** [comment]
What is the command line that you run to launch the tests?

**Comment by agaramudhala** [comment]
Used DEBUG=pw:protocol  along with mvn compile exec cmd

**Comment by yury-s** [comment]
Note that we need `DEBUG=pw:browser` rather than `DEBUG=pw:protocol`. Can you shared the output in that case or you are saying that it's lost somewhere?

**Comment by agaramudhala** [comment]
tried with above cmd **_DEBUG=pw:browser_**
Skipping browsers download because PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD env variable is set. Exception : com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.

**Comment by yury-s** [comment]
We need more information about your setup, can you share the project maybe? It looks like the driver fails to start for some reason but it's hard to tell what could go wrong with such scarce information.

**Comment by yury-s** [comment]
Or can you share a minimal repro?

**Comment by agaramudhala** [comment]
lemme try to recreate the project for sharing since i couldn't share the existing one as os due to organisation restrictions

**Comment by agaramudhala** [comment]
sometimes I have got below err also while running in Jenkins.

java.lang.ClassNotFoundException: com.mycompany.app.Example
     at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
     at java.lang.ClassLoader.loadClass (ClassLoader.java:419)
     at java.lang.ClassLoader.loadClass (ClassLoader.java:352)
     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:246)
     at java.lang.Thread.run (Thread.java:748)

Locally I don't get this error  but while running on jenkins , this error occurs

**Comment by yury-s** [comment]
> sometimes I have got below err also while running in Jenkins.

Something is wrong with your setup on jenkins as some of the classes are not in the classpath. Perhaps they are not properly copied into the docker image.

**Comment by yury-s** [comment]
I'm not familiar with Jenkins, so I would appreciate detailed steps what to do.

**Comment by yury-s** [comment]
Ok, I'd need to install Jenkins to reproduce all this. Can you reproduce the problem with Docker manually to eliminate Jenkins from the setup? Basically just launch docker and run the same command Jenkins would do.

Looking at `Example.java` I see that you launch browser with [`setHeadless(false)`](https://github.com/agaramudhala/pw-java/blob/2aa778c8ef40c230496acce155267f899ca198ec/my-app/src/main/java/com/mycompany/Example.java#L9) which is bound to fail inside docker which doesn't have an X display. Could you remove the options and launch in headless mode?

**Comment by yury-s** [comment]
At this point it's unclear to me how to reproduce it, the setup is quite complex and I feel like the problem should be reproducible without Jenkins if it's a playwrigh issue but the docker image you uploaded doesn't build out of the box, so it's hard to tell what is not working at the later stages. Feel free to open a new issue with a small repro.
