### ISSUE TITLE
[BUG] Failed to create driver with Launch4j

### ISSUE THREAD

**Issue by crysan** [microsoft/playwright-java#640]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Windows 7 Professional 64
- Browser: Chromium

		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>playwright</artifactId>
			<version>1.15.2</version>
		</dependency>

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    	Map<String, String> pathToEnv = new HashMap<String, String>();
		pathToEnv.put("PLAYWRIGHT_BROWSERS_PATH", System.getProperty("user.dir") + "\\browser\\");
		//pathToEnv.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
		
		try (Playwright playwright = Playwright.create(new CreateOptions().setEnv(pathToEnv))) {
			browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
			BrowserContext context = browser.newContext();
			page = context.newPage();
			page.navigate("https://translate.google.com");
			browser.close();
		}
  }
}
```

**Describe the bug**

```
java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
        at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39)
        at com.microsoft.playwright.Playwright.create(Playwright.java:92)
        at Kaspi_Kz.start(Kaspi_Kz.java:135)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.FileSystemNotFoundException: Provider "rsrc" not installed
        at java.nio.file.Paths.get(Unknown Source)
        at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:82)
        at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:38)

        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
        ... 12 more
```

If you run the application through the IDE, then everything works, the browser images are downloaded to the directory and the program is launched.
If you create an EXE file through the Launch4j 3.14 application, an error appears and the application does not work.
I ask for your help!
Thanks!

**Comment by crysan** [comment]
Ok, on this point it is clear.
But let's move on.

Made a BAT file with the following content
`java -jar kaspikz.jar`

I run and an error appears
```
com.microsoft.playwright.PlaywrightException: Error {
  message='spawn UNKNOWN
=========================== logs ===========================
<launching> F:\Parser\_Kaspi_Kz\browser\chromium-920619\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=C:\Users\Home\AppData\Local\Temp\playwright_chromiumdev_profile-jsWGNH --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
============================================================
  name='Error
  stack='Error: spawn UNKNOWN
=========================== logs ===========================
<launching> F:\Parser\_Kaspi_Kz\browser\chromium-920619\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=C:\Users\Home\AppData\Local\Temp\playwright_chromiumdev_profile-jsWGNH --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window
============================================================
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at Object.spawn (child_process.js:553:9)
    at launchProcess (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\utils\processLauncher.js:62:39)
    at Chromium._launchProcess (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\server\browserType.js:206:50)
    at async Chromium._innerLaunch (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\server\browserType.js:125:9)
    at async ProgressController.run (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\server\progress.js:89:22)
    at async Chromium.launch (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\server\browserType.js:81:21)
    at async BrowserTypeDispatcher.launch (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\dispatchers\browserTypeDispatcher.js:48:21)
    at async DispatcherConnection.dispatch (C:\Users\Home\AppData\Local\Temp\playwright-java-5688155483075641006\package\lib\dispatchers\dispatcher.js:349:22)
}
com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:54)
com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:112)
com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:51)
com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:43)
com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:43)
com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:36)
com.microsoft.playwright.BrowserType.launch(BrowserType.java:1041)
Kaspi_Kz.start(Kaspi_Kz.java:136)
com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
java.security.AccessController.doPrivileged(Native Method)
com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
java.lang.Thread.run(Unknown Source)
```

How to be?

**Comment by crysan** [comment]
Thanks!
So I will
