### ISSUE TITLE
[Question] getting this error on trying to run from Jenkins behind a corporate proxy. java.lang.RuntimeException: Failed to create driver

### ISSUE THREAD

**Issue by agaramudhala** [microsoft/playwright-java#647]
### `**java.lang.RuntimeException: Failed to create driver**`
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
 	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39)
 	at com.microsoft.playwright.Playwright.create(Playwright.java:88)
	at com.microsoft.playwright.Playwright.create(Playwright.java:92)

**Comment by agaramudhala** [comment]
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 127
 	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:67)
 	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:39)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39)
 	at com.microsoft.playwright.Playwright.create(Playwright.java:88)
 	at com.microsoft.playwright.Playwright.create(Playwright.java:92)

**Comment by yury-s** [comment]
See [these instructions](https://playwright.dev/java/docs/browsers#install-behind-a-firewall-or-a-proxy).
