### ISSUE TITLE
[BUG] PlayWright after upgrade always trigger timeout and other error

### ISSUE THREAD

**Issue by ylhang** [microsoft/playwright-java#684]
**Context:**
- Playwright Version: 1.15.2->1.16.1
- Operating System: windows 10
- Browser: Chromium

I set the environment variable: PLAYWRIGHT_BROWSERS_PATH=D:\soft\playwright\ms-playwright, then delete the original PlayWright, and then start my spring boot application:  
```java
@RequestMapping(path = "/get1", method = RequestMethod.GET)
    public String get1(@RequestParam("browse") String browse) throws InterruptedException {
        String result="";
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("https://www.baidu.com");
            System.out.println(page.title());
            result=page.title();
        }catch (Throwable ex){
            log.error("error",ex);
        }
        return  result;
    }
```
  report an error often, the error is as follows
```java
com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\server\progress.js:84:26)
    at Chromium.launch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\server\browserType.js:81:38)
    at BrowserTypeDispatcher.launch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\dispatchers\browserTypeDispatcher.js:48:40)
    at DispatcherConnection.dispatch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\dispatchers\dispatcher.js:349:46)
}
	at com.microsoft.playwright.impl.WaitableResult.get(WaitableResult.java:52) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:112) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.BrowserTypeImpl.launchImpl(BrowserTypeImpl.java:51) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.BrowserTypeImpl.lambda$launch$0(BrowserTypeImpl.java:43) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:43) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.BrowserTypeImpl.launch(BrowserTypeImpl.java:36) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.BrowserType.launch(BrowserType.java:1041) ~[playwright-1.15.2.jar:na]
	at com.eastmoney.demo.controller.TestPlaywright.get1(TestPlaywright.java:29) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) [spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.10.jar:5.3.10]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.3.10.jar:5.3.10]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) [tomcat-embed-core-9.0.53.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.10.jar:5.3.10]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [tomcat-embed-core-9.0.53.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.10.jar:5.3.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.10.jar:5.3.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.10.jar:5.3.10]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.10.jar:5.3.10]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.53.jar:9.0.53]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: com.microsoft.playwright.TimeoutError: Error {
  message='Timeout 30000ms exceeded.
  name='TimeoutError
  stack='TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\server\progress.js:84:26)
    at Chromium.launch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\server\browserType.js:81:38)
    at BrowserTypeDispatcher.launch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\dispatchers\browserTypeDispatcher.js:48:40)
    at DispatcherConnection.dispatch (C:\Users\EVERYB~1\AppData\Local\Temp\playwright-java-3052709437170394793\package\lib\dispatchers\dispatcher.js:349:46)
}
	at com.microsoft.playwright.impl.Connection.dispatch(Connection.java:230) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:212) ~[playwright-1.15.2.jar:na]
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101) ~[playwright-1.15.2.jar:na]
	... 60 common frames omitted
```

if i change java code to :
```java
 try (Playwright playwright = create()){
            Browser browser = null;
            BrowserContext browserContext = null;
            Path path = Paths.get("d:\\temp\\playwrightcache");
            while (true) {
                try {
                    req = blockingQueue.poll(2, TimeUnit.SECONDS);
                   if (null == req) {
                        Thread.sleep(200);
                        continue;
                    }
                   BrowserType browserType = playwright.chromium();
                  if (browser == null || !browser.isConnected()) {
                        closeBrowse(browser);
                        browser = browserType.launch(new BrowserType.LaunchOptions().setHeadless(true));
                 }
            }catch (Throwable ex) {
                    log.error(tag + ",consume error", ex);
                } finally {
                    Thread.sleep(5);
                }
}catch (Throwable ex){
            log.error("V3消费错误.......",ex);
        }finally {
            //closePlaywright(playwright);
        }
```
after some times timeout error ,      it will cause the follow error
```java
Cannot find parent object browser-type@3dab228a9b749fd0f8de50926cac1c6c to create browser@743b73b794721874953df36d270cf5e7
```

**Comment by yury-s** [comment]
> report an error often, the error is as follows

The browser fails to start within 30s for some reason. Try running it with `DEBUG=pw:browser` to see if the browser crashes or complains about something.
