### ISSUE TITLE
[REGRESSION]: Regression issue is occuring with the playwright driver

### ISSUE THREAD

**Issue by akashshrimali** [microsoft/playwright-java#738]
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?] 1.13.0
- BAD Playwright Version: [what Playwright version doesn't work any more?] 1.13.0 and 1.17.0
- Operating System: [e.g. Windows, Linux or Mac] Linux
- Extra: [any specific details about your environment]  

**Code Snippet**

		try (Playwright playwright = Playwright.create()) {
		}

Giving error :
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      // ...
    }
  }
}
```

**Describe the bug**
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.

Add any other details about the problem here.

**Comment by akashshrimali** [comment]
Getting following error while running the environment 
 com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:202)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:115)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:82)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:183)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:45)
	at com.microsoft.playwright.Playwright.create(Playwright.java:92)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
