### ISSUE TITLE
[BUG] locator screenshot fails due to internal access 

### ISSUE THREAD

**Issue by maxandersen** [microsoft/playwright-java#787]
**Context:**
- Playwright Version: com.microsoft.playwright:playwright:1.17.0
- Operating System: mac
- Browser: firefox
- Java version: Java 17

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
page.locator("#board").screenshot(new Locator.ScreenshotOptions().setPath(Paths.get("somename.png")));
```

**Describe the bug**

above code fails due to gson trying to access private fields.

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.nio.fs.UnixFileSystem sun.nio.fs.UnixPath.fs accessible: module java.base does not "opens sun.nio.fs" to unnamed module @1a27aae3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at com.microsoft.playwright.impl.Utils.convertViaJson(Utils.java:41)
	at com.microsoft.playwright.impl.LocatorImpl.screenshot(LocatorImpl.java:269)
	at pw.dasbrain.wordle.Wordle.share(main.java:162)
	at pw.dasbrain.wordle.main.main(main.java:67)
Exception in thread "main" com.microsoft.playwright.TimeoutError: Timeout 30000ms exceeded
	at com.microsoft.playwright.impl.WaitableTimeout.get(WaitableTimeout.java:41)
	at com.microsoft.playwright.impl.WaitableRace.get(WaitableRace.java:44)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:103)
	at com.microsoft.playwright.impl.PageImpl.waitForEventWithTimeout(PageImpl.java:535)
	at com.microsoft.playwright.impl.PageImpl.waitForCloseImpl(PageImpl.java:454)
	at com.microsoft.playwright.impl.PageImpl.lambda$waitForClose$0(PageImpl.java:447)
	at com.microsoft.playwright.impl.WaitForEventLogger.get(WaitForEventLogger.java:46)
	at com.microsoft.playwright.impl.ChannelOwner.withWaitLogging(ChannelOwner.java:72)
	at com.microsoft.playwright.impl.PageImpl.waitForClose(PageImpl.java:447)
	at com.microsoft.playwright.Page.waitForClose(Page.java:5742)
	at pw.dasbrain.wordle.Wordle.waitForClose(main.java:171)
	at pw.dasbrain.wordle.main.main(main.java:76)
```

**Comment by maxandersen** [comment]
never mind. fixed in 1.18.0.
