### ISSUE TITLE
Browser are not installed using install command ( Maven )

### ISSUE THREAD

**Issue by rajukthomas** [microsoft/playwright-java#799]
I am using playwright version 1.18.0 on window 7 OS and JAVA 8 but am not able to install browsers. It fails with below errors

<dependencies>
		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>playwright</artifactId>
			<version>1.18.0</version>
		</dependency>

		
		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>driver-bundle</artifactId>
			<version>1.18.0</version>
		</dependency>
	</dependencies>
Command Executed : mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

[INFO] Building ch-playwright 1.0.0-alpha
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ ch-playwright ---
[WARNING]
java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
        at com.microsoft.playwright.CLI.main(CLI.java:32)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511
        at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:72)
        at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:45)
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
        ... 3 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.213 s
[INFO] Finished at: 2022-02-04T09:51:52-06:00
[INFO] Final Memory: 12M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project ch-playwright: An exception occured while executing the Java class. Failed to create driver
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project ch-playwright: An exception occured while e
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. Failed to create driver
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:311)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.RuntimeException: Failed to create driver
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
        at com.microsoft.playwright.CLI.main(CLI.java:32)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: -1073741511
        at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:72)
        at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:45)
        at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52)
        ... 3 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by yury-s** [comment]
window 7 is deprecated and not supported by Playwright.
