### ISSUE TITLE
[BUG] Unclear assertion message for strings

### ISSUE THREAD

**Issue by denis-domanskii** [microsoft/playwright-java#807]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Mac
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
import com.microsoft.playwright.*;

public class ExampleReproducible {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      BrowserContext context = browser.newContext();
      Page page = context.newPage();
      page.navigate("http://playwright.dev");
      assertThat(page).hasTitle("Wrong title");
    }
  }
}
```

**Describe the bug**

It will be nice to have more friendly assertion output, which is clear and contain critical items such a:
- Expected value
- Actual value
- Error type
- Error place (in test file)

Current assertion message doesn't have expected value , but has a very long and unclear output with many duplicated strings.

Expected output:
```
Error: Page title assertion failed

Expected substring: "Wrong title"
Received string:    "Past and reliable end-to-end testing for modern web apps | Playwright"

      at org.example.PrintTitle.main(PrintTitle.java:29)
      at com.microsoft.playwright.assertions.PageAssertions.hasTitle(PageAssertions.java:86)
      at com.microsoft.playwright.impl.PageAssertionsImpl.hasTitle(PageAssertionsImpl.java:44)
      at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:41)
      ...
```

Actual output:
```
Exception in thread "main" org.opentest4j.AssertionFailedError: Page title expected to be
Call log:
Locator.expect with timeout 5000ms
waiting for selector ":root"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
  selector resolved to <html lang="en" dir="ltr" data-theme="dark" data-react…>…</html>
  unexpected value "Fast and reliable end-to-end testing for modern web apps | Playwright"
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:70)
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:50)
	at com.microsoft.playwright.impl.AssertionsBase.expectImpl(AssertionsBase.java:41)
	at com.microsoft.playwright.impl.PageAssertionsImpl.hasTitle(PageAssertionsImpl.java:44)
	at com.microsoft.playwright.assertions.PageAssertions.hasTitle(PageAssertions.java:86)
	at org.example.PrintTitle.main(PrintTitle.java:29)
```

BTW, I want to say thank you, playwright folks, for this Java implementation, you doing great job! Playwright for Java allow us to write e2e tests based on in-process backend integration tests. It's magic when you can manipulate service on the fly via code and verify it on frontend via Playwright. Unit-tests speed, e2e-test coverage :)

**Comment by yury-s** [comment]
When running the test from an IDE it should show expected and actual values:
![image](https://user-images.githubusercontent.com/9798949/153664337-8e687a86-2c1a-4143-9f37-d77749085497.png)

They are clearly missing though when running from terminal or not as a unit test.

**Comment by denis-domanskii** [comment]
Thank you very much, Yury!
