### ISSUE TITLE
[QUESTION] Spring Boot classloader and non-main thread shenanigans

### ISSUE THREAD

**Issue by Tristan971** [microsoft/playwright-java#822]
**Context:**
- Playwright Version: 1.19.0 (but irrelevant)
- Operating System: Linux (but irrelevant)
- Browser: All
- Extra: Related to Spring Boot classloaders

To be honest, I'm not sure it's even a concern for Playwright per-se, just thought I'd put it here to help out another lost soul at least (or a maintainer if you feel like it's a problem, idk).

It's similar to #306 in spirit.

Turns out Spring Boot sets up its own fancy classloader (presumably to deal with how spring-boot-maven-plugin builds executable JARs?), which is all fine, but this doesn't propagate to "manually" created threads.

Consider the following (ignore the lack of try-with-resources or thread mgmt but don't do it this way in production ofc):
```java
private static final ExecutorService SVC = Executors.newWorkStealingPool(2);

public void test() {
  svc.submit(() -> Playwright.create().chromium().launch());
}
```

This will fail because, just like in #306 you will run into `Thread.currentThread().getContextClassLoader().getResource("driver/linux")` returning `null`. This is because the threads of your executor service don't share the same classloader as the app container.

![2022-02-20 19_37_24-Evaluate (fedoraremix)](https://user-images.githubusercontent.com/875533/154861354-a1183b1e-bccd-4ae2-adfe-5d2c21ce8063.png)

And this then throws:
```java
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:85) ~[driver-bundle-1.19.0.jar!/:1.19.0]
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:44) ~[driver-bundle-1.19.0.jar!/:1.19.0]
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) ~[driver-1.19.0.jar!/:1.19.0]
	... 18 common frames omitted
```

If however you make sure to run the initialization step within a managed bean like so:
```java
@Service
public class BrowserScreenshotService implements InitializingBean {

    private static final Logger LOGGER = LoggerFactory.getLogger(BrowserScreenshotService.class);

    private final ExecutorService executorService;
    private final BrowserSettings browserSettings;

    public BrowserScreenshotService(BrowserSettings browserSettings) {
        this.browserSettings = browserSettings;
        executorService = Executors.newWorkStealingPool(browserSettings.count());
    }

    @Override
    public void afterPropertiesSet() {
        try (
            Playwright playwright = Playwright.create();
            Browser chromium = playwright.chromium().launch()
        ) {
            LOGGER.info("Loaded Chromium {}", chromium.version());
        } catch (Exception e) {
            throw new IllegalStateException("Failed initializing Chromium via Playwright!", e);
        }
    }

...
```

Then Playwright driver initialization happens with the correct classloader (as it pulls it from `Thread#getContextClassLoader` and initialization is called in the main thread) and everything works just fine.

![2022-02-20 19_43_02-Evaluate (fedoraremix)](https://user-images.githubusercontent.com/875533/154861217-7b867bca-6ee9-41ba-8a5d-7ea4c5bc6f1f.png)

And indeed in the logs I see:
```
2022-02-20 19:44:18.036  INFO [                                main] BrowserScreenshotSer : Loaded Chromium 100.0.4863.0
```

(and it all works fine)

It's probably also possible to do `Thread.currentThread().setContextClassLoader()` in the child threads but that sounded more cumbersome.

**Comment by Tristan971** [comment]
Closing as it's mostly informational.
