### ISSUE TITLE
[BUG] java.lang.RuntimeException: Failed to create driver

### ISSUE THREAD

**Issue by satya081** [microsoft/playwright-java#853]
**Context:**
- Playwright Version: 1.17.2
- Operating System: [e.g. Windows]
- Browser: [Chrome]
- Extra: standalone Selenium Grid 4 is set up in a windows remote machine.
Getting below error while running testcase through standalone selenium grid 4(created in a remote windows machine)
playwright version used 1.17.2
```
[INFO] Running org.example.AppTest
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:39)
	at com.microsoft.playwright.Playwright.create(Playwright.java:92)
```
code snippet
---------------
```java
public void shouldAnswerWithTrue()
{
    List<String> list=new ArrayList<String>();
    list.add("--start-maximized");
    Map<String, String> env = new HashMap<>();
    env.put("SELENIUM_REMOTE_URL", "http://testing.net.int:4444/");
    try(Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(env))){
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false).setSlowMo(100).setArgs(list));
        BrowserContext browserContext = browser.newContext();
        Page page = browserContext.newPage();
    }
    catch (Exception e) {
            e.printStackTrace();
        }
}
```

**Comment by yury-s** [comment]
Do you run the test via Maven or use some custom packaging?

**Comment by yury-s** [comment]
Does it reproduce if you remove `.setHeadless(false)`? Does the same error occur if you don't pass env to `Playwright.create` ? Also try running with `DEBUG=pw:browser` to see extra logs. It'd be helpful if you could share a repro.

**Comment by satya081** [comment]
First i removed .setHeadless(false), but same error occurs.And its not going to Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setSlowMo(100).setArgs(list)); its failing at try(Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(env))){
Then i removed env variable and added SELENIUM_REMOTE_URL=http://testing.ext.int:4444 in the environment variable and ran the testcase like this try(Playwright playwright = Playwright.create()){ still same issue occurs. Then added DEBUG=pw:browser in the environment variables no extra log came in intellij console. Could you please help me.

**Comment by yury-s** [comment]
> Then added DEBUG=pw:browser in the environment variables no extra log came in intellij console.

Try running it with maven from terminal and without SELENIUM_REMOTE_URL for now, just to see if local browser works.

> Could you please help me.

We need a repro to help, the error is too generic.

**Comment by satya081** [comment]
i ran through terminal using command mvn test after removing SELENIUM_REMOTE_URL . I am getting same error as below. As i dont admin privileges in corporate laptop driver cannot be initiated from there. By using selenium 4 also i cannot initiate my chrome driver in my local machine. Thats y i am using selenium grid 4. And the same selenium grid i want to try with playwright for one of the scenario(HTML5 drag and drop) which is not possible in selenium 4 now.

![image](https://user-images.githubusercontent.com/32022027/158662998-c650ab0e-34f9-4666-b2c0-09fd052eea0f.png)

**Comment by satya081** [comment]
Any update on this

**Comment by yury-s** [comment]
> if I am using same repo in another machine(amazon workspace), local chrome browser opens and is working fine with same playwright version.

It seems that browser download fails, try updating to playwright 1.20.1 and running with  [PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD](https://playwright.dev/java/docs/next/browsers#skip-browser-downloads) to skip the failing step.

**Comment by satya081** [comment]
As you said I upgraded the playwright version to 1.20.1 and used PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 in environment variables and ran with command mvn test and I got following error.
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.example.AppTest
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:75)
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:157)
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101)
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105)
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:76)
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:138)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:47)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at com.microsoft.playwright.Playwright.create(Playwright.java:100)
	at org.example.AppTest.shouldAnswerWithTrue(AppTest.java:30)

**Comment by yury-s** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by satya081** [comment]
Any update on this?

**Comment by satya081** [comment]
Hello [yury-s](https://github.com/yury-s) Did you solve this issue?

**Comment by yury-s** [comment]
We need more info to act on this, can you run with DEBUG="pw:install,pw:channel" and share the logs?

**Comment by satya081** [comment]
@yury-s As you suggested i have added DEBUG="pw:install,pw:channel" i am getting below logs.

![image](https://user-images.githubusercontent.com/32022027/164317151-555f5c89-034e-4588-aa37-9cdb3eb6a4ed.png)

C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\VFS\ProgramFilesX64\Java\jdk8\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\dasatya\workspace\playwrightDemo "-Dmaven.home=C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\plugins\maven\lib\maven3\bin\m2.conf" "-Dmaven.ext.class.path=C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\plugins\maven\lib\maven-event-listener.jar" "-javaagent:C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\lib\idea_rt.jar=53162:C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;C:\ProgramData\AppV\1E69598A-0916-46CF-A75B-FBE77BCC81EA\5D0E86B0-3D1F-49EA-87B4-A2E648801851\Root\IntelliJ IDEA Community Edition 2021.1.1\plugins\maven\lib\maven3\boot\plexus-classworlds.license" org.codehaus.classworlds.Launcher -Didea.version=2021.1.1 test
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.example:playwrightDemo:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> version 4.11 vs 4.13 @ line 33, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> version 4.11 vs 4.13 @ line 39, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------< org.example:playwrightDemo >---------------------
[INFO] Building playwrightDemo 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ playwrightDemo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\dasatya\workspace\playwrightDemo\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ playwrightDemo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ playwrightDemo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\dasatya\workspace\playwrightDemo\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ playwrightDemo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ playwrightDemo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.example.AppTest
2022-04-20T20:26:41.514Z pw:install created DriverJar: C:\Users\dasatya\AppData\Local\Temp\1\playwright-java-8170381812242527446
2022-04-20T20:26:41.518Z pw:install initializing driver
2022-04-20T20:26:43.592Z pw:install extracted driver from jar to C:\Users\dasatya\AppData\Local\Temp\1\playwright-java-8170381812242527446\playwright.cmd
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:61)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40)
	at com.microsoft.playwright.Playwright.create(Playwright.java:96)
	at org.example.AppTest.shouldAnswerWithTrue(AppTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.RuntimeException: Failed to install browsers, exit code: 1
	at com.microsoft.playwright.impl.DriverJar.installBrowsers(DriverJar.java:76)
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:48)
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:57)
	... 31 more
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.208 s - in org.example.AppTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.019 s
[INFO] Finished at: 2022-04-20T22:26:46+02:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0

**Comment by satya081** [comment]
[yury-s] any update on this?

**Comment by yury-s** [comment]
According to the log running driver commands from the temp folder fails for some reason. Can you run it under debugger, pause at line DriverJar.java:47 and then try running command ` C:\Users\dasatya\AppData\Local\Temp\1\playwright-java-8170381812242527446\playwright.cmd install` from terminal to see why it fails (replace location with the actual path for that playwright run)? My hunch is that there is some permission issue or some policy/antivirus restriction that prevents the launch.

**Comment by satya081** [comment]
Really appreciate for your quick reply. Sorry to bother you more. I did not get the point mentioned  by you " That command is supposed to download 3 browsers on the first run and cache them locally". But if you see the main issue description I am trying to connect selenium grid(which is a different remote machine) from my local machine. so browser should downloaded in remote machine right not locally? for your information the selenium grid is working fine when i am running testcases from selenium 4 code but same selenium grid is not working from playwright code. if this is related to permission issue or a policy/antivirus restriction then selenium grid should not work from selenium code as well right? Could you please explain it in detail for better understanding or else Could you please explain playwright to selenium grid connection architecture in detail how it is different from selenium to selenium grid connection architecture. Thank you so much. Waiting for your answer.

**Comment by elfiorr** [comment]
I have the same problem on local machine. Any new ideas?

**Comment by yury-s** [comment]
> I did not get the point mentioned by you " That command is supposed to download 3 browsers on the first run and cache them locally". But if you see the main issue description I am trying to connect selenium grid(which is a different remote machine) from my local machine. so browser should downloaded in remote machine right not locally?

Sorry, you are right, looks like playwright tries to download browsers unconditionally(on local machine) even if you are connecting to Selenium grid. Can you try disabling that behavior by running your code with [`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`](https://playwright.dev/java/docs/next/browsers#skip-browser-downloads) environment variable and see if it helps? It it helps we'll update playwright to not try loading browsers if SELENIUM_REMOTE_URL is specified.

> for your information the selenium grid is working fine when i am running testcases from selenium 4 code but same selenium grid is not working from playwright code. if this is related to permission issue or a policy/antivirus restriction then selenium grid should not work from selenium code as well right?

I believe it has something to do with the local playwright setup, we should make sure that it can run the driver successfully, as it's the driver who establishes connection to the grid.

**Comment by cmeng-git** [comment]
I too faced the same problem when trying to use playwright for a simple web scrappy (see attached source below) on android device.

On tracing, found that the returned resource path is "driver/linux-arm64", but classloader.getResource returns null; hence .toURI throws an exception.
> classloader.getResource("driver/" + platformDir())

I see that the driver-bundle v1.22.0 jar does contain the required path i.e. "driver/linux-arm64".
Please advice if playwright is also designed for use with android OS?
If so, any advice to resolve the problem.

```
//======== Driver.jar =========
  private void extractDriverToTempDir() throws URISyntaxException, IOException {
    ClassLoader classloader = Thread.currentThread().getContextClassLoader();
    URI originalUri = classloader.getResource("driver/" + platformDir()).toURI();
    URI uri = maybeExtractNestedJar(originalUri);
    ....
}
```

```
    public static String getSource(String url) throws IOException
    {
        String content = null;
        try (Playwright playwright = Playwright.create()) {
            final BrowserType chromium = playwright.chromium();
            final Browser browser = chromium.launch();
            final Page page = browser.newPage();
            page.navigate(url);

            content = page.content();
            browser.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return content;
    }
```
```
2022-06-24 08:16:54.114 6940-7088/org.cog.hymnchtv W/System.err: java.lang.RuntimeException: Failed to create driver
2022-06-24 08:16:54.115 6940-7088/org.cog.hymnchtv W/System.err:     at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:61)
2022-06-24 08:16:54.115 6940-7088/org.cog.hymnchtv W/System.err:     at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40)
2022-06-24 08:16:54.115 6940-7088/org.cog.hymnchtv W/System.err:     at com.microsoft.playwright.Playwright.create(Playwright.java:96)
2022-06-24 08:16:54.116 6940-7088/org.cog.hymnchtv W/System.err:     at com.microsoft.playwright.Playwright.create(Playwright.java:100)
2022-06-24 08:16:54.116 6940-7088/org.cog.hymnchtv W/System.err:     at org.cog.hymnchtv.utils.SocketConnection.getSource(SocketConnection.java:108)
```

**Comment by yury-s** [comment]
> I too faced the same problem when trying to use playwright for a simple web scrappy (see attached source below) on android device.
> 
> On tracing, found that the returned resource path is "driver/linux-arm64", but classloader.getResource returns null; hence .toURI throws an exception.
> 
>

Do you run the tests with Maven or you have a custom deployment? Note that depending on what Java runtime you use the classloaders may behave differently and may require extra configuration / build steps to make the driver loading work.  Since you run it on Android it's likely a different issue even though the symptom is similar, feel free to open a separate bug for it.

**Comment by anthonyalayo** [comment]
I am having the same problem. I'm not sure why this issue was closed?

**Comment by anthonyalayo** [comment]
I am having the same problem. I'm not sure why this issue was closed?

@satya081 @elfiorr did you have a solution?

**Comment by BatonSudbyGit** [comment]
public static void browserSet(String browsers) {
            Map<String, String> env = new HashMap<>();
            env.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1");
            Playwright.CreateOptions createOptions = new Playwright.CreateOptions();
            createOptions.setEnv(env);
            browser = Playwright.create(createOptions).chromium().launch(
                    new BrowserType.LaunchOptions()
                            .setExecutablePath(Paths.get("Path/to/browser.exe")))
                            .setHeadless(false)
                            .setChromiumSandbox(true));
            context = browser.newContext(
                    new Browser.NewContextOptions()
                            .setViewportSize(1800, 1080)
            );
      }

**Comment by GirishbKulkarni** [comment]
I am facing similar issue; any updates ?

**Comment by generactesting** [comment]
From Yesterday... I too facing same issue. Can any one help me on this

Browser name is: chromium
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
	at com.microsoft.playwright.Playwright.create(Playwright.java:110)
	at com.microsoft.playwright.Playwright.create(Playwright.java:114)
	at com.qa.factory.PlaywrightFactory2.initBrowser(PlaywrightFactory2.java:30)
	at com.qa.base.BaseTest.setup(BaseTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:663)
	at org.testng.TestRunner.beforeRun(TestRunner.java:652)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.RuntimeException: Failed to extract driver from jar:file:/C:/Users/songolu/.m2/repository/com/microsoft/playwright/driver-bundle/1.36.0/driver-bundle-1.36.0.jar!/driver/win32_x64, full uri: jar:file:/C:/Users/songolu/.m2/repository/com/microsoft/playwright/driver-bundle/1.36.0/driver-bundle-1.36.0.jar!/driver/win32_x64
	at com.microsoft.playwright.impl.driver.jar.DriverJar.lambda$extractDriverToTempDir$0(DriverJar.java:154)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.extractDriverToTempDir(DriverJar.java:134)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:66)
	at com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
	... 31 more
Caused by: java.io.IOException: There is not enough space on the disk
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:68)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
	at java.base/java.io.InputStream.transferTo(InputStream.java:783)
	at java.base/java.nio.file.Files.copy(Files.java:3171)
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126)
	at java.base/java.nio.file.Files.copy(Files.java:1308)
	at com.microsoft.playwright.impl.driver.jar.DriverJar.lambda$extractDriverToTempDir$0(DriverJar.java:147)
	... 45 more

**Comment by Sharmila185** [comment]
My code is here,

           Playwright playwright = Playwright.create();
	   Browser browser = playwright.chromium().launch(
			   new BrowserType.LaunchOptions().setHeadless(false).setChannel("Chrome"));
	   Page page = browser.newPage();
	   page.navigate("sprsika.simplesolve.com");
	   String title = page.title();
	   System.out.println(title);
	   
	   page.close();
	   browser.close();
	   playwright.close();


I am facing the same issue,


        Exception in thread "main" java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
	at com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
	at com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)

**Comment by andyyapwl** [comment]
> @anthonyalayo public static void browserSet(String browsers) { Map<String, String> env = new HashMap<>(); env.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD", "1"); Playwright.CreateOptions createOptions = new Playwright.CreateOptions(); createOptions.setEnv(env); browser = Playwright.create(createOptions).chromium().launch( new BrowserType.LaunchOptions() .setExecutablePath(Paths.get("Path/to/browser.exe"))) .setHeadless(false) .setChromiumSandbox(true)); context = browser.newContext( new Browser.NewContextOptions() .setViewportSize(1800, 1080) ); }

u saved my life, thanks!

**Comment by phaquatun** [comment]
playwright for java very slow and bad .
