### ISSUE TITLE
[BUG] SpringBoot - Failed to extract driver from 

### ISSUE THREAD

**Issue by marcelrufino** [microsoft/playwright-java#884]
**Context:**
- Playwright Version: 1.20.1
- Operating System: MacOS Big Sur 11.6.5
- Browser: All
- Extra: Using SpringBoot 2.6.5

My code:
```java
new Runnable() {

			public void run() {

				try (Playwright playwright = Playwright.create()) {
```

My pom.xml Playwright configuration:
```xml
		<dependency>
			<groupId>com.microsoft.playwright</groupId>
			<artifactId>playwright</artifactId>
			<version>1.20.1</version>
		</dependency>
```
Error:
```java
java.lang.RuntimeException: Failed to create driver
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:54) ~[driver-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:40) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.Playwright.create(Playwright.java:100) ~[playwright-1.20.1.jar:1.20.1]
	at com.marcelrufino.sentinel.ws.service.implementations.MonitorServiceImpl$1.run(MonitorServiceImpl.java:171) ~[classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.17.jar:5.3.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.RuntimeException: Failed to extract driver from jar:file:/Users/marcel/.m2/repository/com/microsoft/playwright/driver-bundle/1.20.1/driver-bundle-1.20.1.jar!/driver/mac, full uri: jar:file:/Users/marcel/.m2/repository/com/microsoft/playwright/driver-bundle/1.20.1/driver-bundle-1.20.1.jar!/driver/mac
	at com.microsoft.playwright.impl.DriverJar.lambda$extractDriverToTempDir$0(DriverJar.java:110) ~[driver-bundle-1.20.1.jar:1.20.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at com.microsoft.playwright.impl.DriverJar.extractDriverToTempDir(DriverJar.java:96) ~[driver-bundle-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.DriverJar.initialize(DriverJar.java:44) ~[driver-bundle-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.Driver.ensureDriverInstalled(Driver.java:52) ~[driver-1.20.1.jar:1.20.1]
	... 11 common frames omitted
Caused by: java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:820) ~[na:na]
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:800) ~[na:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2218) ~[jdk.zipfs:na]
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2155) ~[jdk.zipfs:na]
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[na:na]
	at java.base/java.io.InputStream.transferTo(InputStream.java:782) ~[na:na]
	at java.base/java.nio.file.Files.copy(Files.java:3171) ~[na:na]
	at java.base/java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126) ~[na:na]
	at java.base/java.nio.file.Files.copy(Files.java:1308) ~[na:na]
	at com.microsoft.playwright.impl.DriverJar.lambda$extractDriverToTempDir$0(DriverJar.java:103) ~[driver-bundle-1.20.1.jar:1.20.1]
	... 24 common frames omitted
```

The directory created by Driver Extraction only contains **node**:

-rw-r--r--  1 marcel  staff   437K  7 Abr 09:33 node
➜  playwright-java-716058017435776150

**Comment by marcelrufino** [comment]
Using alternative described on [https://github.com/microsoft/playwright-java/issues/403#issuecomment-827861784](url), providing a path to manually installed driver via [playwright.cli.dir](https://github.com/microsoft/playwright-java/blob/779d50ca532d12a5a2f48fc45d0a113324d7c62a/driver/src/main/java/com/microsoft/playwright/impl/Driver.java#L59) system property, I'm getting the error bellow:

```
com.microsoft.playwright.PlaywrightException: Failed to read message
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:79) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.Connection.processOneMessage(Connection.java:157) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.ChannelOwner.runUntil(ChannelOwner.java:101) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:105) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.Connection$Root.initialize(Connection.java:76) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:138) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:47) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.Playwright.create(Playwright.java:96) ~[playwright-1.20.1.jar:1.20.1]
	at com.microsoft.playwright.Playwright.create(Playwright.java:100) ~[playwright-1.20.1.jar:1.20.1]
	at com.marcelrufino.sentinel.ws.service.implementations.MonitorServiceImpl$1.run(MonitorServiceImpl.java:171) ~[classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.17.jar:5.3.17]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1679) ~[na:na]
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:435) ~[na:na]
	at com.microsoft.playwright.impl.PipeTransport.poll(PipeTransport.java:68) ~[playwright-1.20.1.jar:1.20.1]
	... 17 common frames omitted
```

➜  playwright-java-716058017435776150 ps ax | grep node
 9070   ??  S      0:00.44 /private/tmp/playwright/node /private/tmp/playwright/package/lib/cli/cli.js run-driver
 9075   ??  S      0:00.43 /private/tmp/playwright/node /private/tmp/playwright/package/lib/cli/cli.js run-driver
 9151   ??  S      0:00.93 /private/tmp/playwright/node /private/tmp/playwright/package/lib/cli/cli.js run-driver
 9200 s000  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn node

**Comment by mxschmitt** [comment]
Closing as part of the triage.
