### ISSUE TITLE
[BUG]Error: EPIPE: broken pipe, write

### ISSUE THREAD

**Issue by shahrihan** [microsoft/playwright-java#886]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
-Maven with Java +Cucumber
- Browser: Chromium
Trying :  page.waitForLoadState();
              System.out.println(page.title());
             

**Describe the bug**

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Transport.send (C:\Users\NIGORA~1.MAM\AppData\Local\Temp\playwright-java-3251920591875641209\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\NIGORA~1.MAM\AppData\Local\Temp\playwright-java-3251920591875641209\package\lib\cli\driver.js:67:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\NIGORA~1.MAM\AppData\Local\Temp\playwright-java-3251920591875641209\package\lib\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\NIGORA~1.MAM\AppData\Local\Temp\playwright-java-3251920591875641209\package\lib\dispatchers\dispatcher.js:108:22)
    at CRBrowserContext.<anonymous> (C:\Users\NIGORA~1.MAM\AppData\Local\Temp\playwright-java-3251920591875641209\package\lib\dispatchers\browserContextDispatcher.js:115:16)
    at CRBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
The batch file cannot be found.

**Comment by mmani648** [comment]
i am doing same thing with threads

**Comment by NikkTod** [comment]
I am getting the same error, although the test is passing.

Playwright Version: 1.21.0
Operating System: Windows 10
-Maven with Java +Cucumber
Browser: Chromium  (tests run on Chrome installed on my machine)
Version 100.0.4896.127

The error comes in the end after the test,  when I start it with 'mvn test' 

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.718 s - in runner.CucumberRunnerTest

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\xxx\AppData\Local\Temp\playwright-java-2156481606678164555\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\xxx\AppData\Local\Temp\playwright-java-2156481606678164555\package\lib\cli\driver.js:63:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\xxx\AppData\Local\Temp\playwright-java-2156481606678164555\package\lib\server\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\xxx\AppData\Local\Temp\playwright-java-2156481606678164555\package\lib\server\dispatchers\dispatcher.js:108:22)
    at CRBrowserContext.<anonymous> (C:\Users\xxx\AppData\Local\Temp\playwright-java-2156481606678164555\package\lib\server\dispatchers\browserContextDispatcher.js:132:16)
    at CRBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
The batch file cannot be found.
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by mmani648** [comment]
yeah i switched to selenium

**Comment by yury-s** [comment]
We need more information to act on this report, it's hard to tell what's going on without seeing the code. Please file a new issue with a reproducible example when you have it and link to this one!

**Comment by kalaiArasi320** [comment]
I am using playwright for my automation. I am facing new issue since last week. 

issue
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Transport.send (C:\Users\KALAI~1.NEE\AppData\Local\Temp\playwright-java-8577992516776778709\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\KALAI~1.NEE\AppData\Local\Temp\playwright-java-8577992516776778709\package\lib\cli\driver.js:67:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\KALAI~1.NEE\AppData\Local\Temp\playwright-java-8577992516776778709\package\lib\dispatchers\dispatcher.js:187:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\KALAI~1.NEE\AppData\Local\Temp\playwright-java-8577992516776778709\package\lib\dispatchers\dispatcher.js:108:22)
    at CRBrowserContext.<anonymous> (C:\Users\KALAI~1.NEE\AppData\Local\Temp\playwright-java-8577992516776778709\package\lib\dispatchers\browserContextDispatcher.js:102:81)
    at CRBrowserContext.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
The batch file cannot be found.
The batch file cannot be found.

**Comment by anhtester** [comment]
**I have the same problem**

"C:\Program Files\Java\jdk-17.0.4.1\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.1\lib\idea_rt.jar=60289:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.1\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.2.1\plugins\testng\lib\testng-rt.jar;D:\ANHTESTER\PlaywrightJava\PlaywrightJava\target\test-classes;D:\ANHTESTER\PlaywrightJava\PlaywrightJava\target\classes;C:\Users\Admin\.m2\repository\com\microsoft\playwright\playwright\1.27.1\playwright-1.27.1.jar;C:\Users\Admin\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\Admin\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\Admin\.m2\repository\com\microsoft\playwright\driver\1.27.1\driver-1.27.1.jar;C:\Users\Admin\.m2\repository\com\microsoft\playwright\driver-bundle\1.27.1\driver-bundle-1.27.1.jar;C:\Users\Admin\.m2\repository\org\testng\testng\7.6.1\testng-7.6.1.jar;C:\Users\Admin\.m2\repository\com\google\code\findbugs\jsr305\3.0.2\jsr305-3.0.2.jar;C:\Users\Admin\.m2\repository\com\beust\jcommander\1.82\jcommander-1.82.jar;C:\Users\Admin\.m2\repository\org\webjars\jquery\3.6.0\jquery-3.6.0.jar;C:\Users\Admin\.m2\repository\org\slf4j\slf4j-api\2.0.3\slf4j-api-2.0.3.jar;C:\Users\Admin\.m2\repository\org\slf4j\slf4j-simple\2.0.3\slf4j-simple-2.0.3.jar" com.intellij.rt.testng.RemoteTestNGStarter -usedefaultlisteners false -socket60288 @w@C:\Users\Admin\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\Admin\AppData\Local\Temp\idea_testng.tmp
[main] INFO org.testng.internal.Utils - [TestNG] Running:
  D:\ANHTESTER\PlaywrightJava\PlaywrightJava\suites\LoginTest.xml

Create Chromium browser...
Create Chromium browser...

===============================================
SuiteLoginTest
Total tests run: 2, Passes: 2, Failures: 0, Skips: 0
===============================================

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at PipeTransport.send (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\cli\driver.js:65:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\server\dispatchers\dispatcher.js:252:10)
    at DispatcherConnection.sendEvent (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\server\dispatchers\dispatcher.js:204:10)
    at PageDispatcher._dispatchEvent (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\server\dispatchers\dispatcher.js:122:22)
    at Page.<anonymous> (C:\Users\Admin\AppData\Local\Temp\playwright-java-14998909857069749625\package\lib\server\dispatchers\pageDispatcher.js:78:71)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
The batch file cannot be found.
The batch file cannot be found.

Process finished with exit code 0
