### ISSUE TITLE
com.microsoft.playwright.PlaywrightException: Source root directory must be specified via PLAYWRIGHT_JAVA_SRC environment variable when source collection is enabled

### ISSUE THREAD

**Issue by deepanmahalingam** [microsoft/playwright-java#944]
'm trying to run my first Playwright program using java and i'm getting below error, I'm not sure what i'm missing out and I'm running mu code in Intlij

Playwright playwright = Playwright.create();
        Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
        BrowserContext browserContext = browser.newContext();
        browserContext.tracing().start(new Tracing.StartOptions().setScreenshots(true).setSnapshots(true).setSources(true));
        Page page = browser.newPage();
        page.navigate("https://www.saucedemo.com/");
        
Im getting below error, can any one help
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Source root directory must be specified via PLAYWRIGHT_JAVA_SRC environment variable when source collection is enabled
    at com.microsoft.playwright.impl.TracingImpl.startImpl(TracingImpl.java:95)
    at com.microsoft.playwright.impl.TracingImpl.lambda$start$0(TracingImpl.java:69)
    at com.microsoft.playwright.impl.LoggingSupport.lambda$withLogging$0(LoggingSupport.java:36)
    at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:47)
    at com.microsoft.playwright.impl.ChannelOwner.withLogging(ChannelOwner.java:79)
    at com.microsoft.playwright.impl.LoggingSupport.withLogging(LoggingSupport.java:35)
    at com.microsoft.playwright.impl.TracingImpl.start(TracingImpl.java:69)
    at Sample.main(Sample.java:12)

can any one please help??

**Comment by yury-s** [comment]
You a trying to collect traces with source code which means that Playwright needs to know where your source code is. Currently this is implemented via the environment variable, so you can run the code with `PLAYWRIGHT_JAVA_SRC=/path/to/my/project/src` or you can omit setSources option.

See documentation for [setSources](https://playwright.dev/java/docs/api/class-tracing#tracing-start-option-sources) option.

**Comment by deepanmahalingam** [comment]
Thanks alot @yury-s . your help is much appreciated
