### ISSUE TITLE
[BUG]EPIPE: broken pipe, write

### ISSUE THREAD

**Issue by ashirbad1986** [microsoft/playwright-java#949]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows-11
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
package testcontext;

import com.google.inject.Inject;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Frame;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.PlaywrightException;
import com.microsoft.playwright.Browser.NewContextOptions;

import io.cucumber.guice.ScenarioScoped;
import io.cucumber.java.Scenario;
import utils.ExcelReading;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.testng.asserts.SoftAssert;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

@SuppressWarnings("unused")
@ScenarioScoped
public class TestContext {

public void invokeDriver(String browserName) {

		try {
			
			long duration = Long.valueOf(config.getConfigValue().getString("implicitwait"));
			String chromePath = null;
			String chromeHeadlessPath = null;

			
			
			
			switch (browserName.toLowerCase()) {
			case "chrome":				
				
				try {
					
					Playwright playwright = Playwright.create();
					BrowserType chromium = playwright.chromium();
					
					Browser browser = chromium.launch(new BrowserType.LaunchOptions()
							.setChannel("chrome")
							.setHeadless(false)
							.setArgs(List.of("--start-maximized", "--disable-web-security"))
							);
					BrowserContext context = browser.newContext(new NewContextOptions().setViewportSize(null));

					context.setDefaultTimeout(60000);
					this.page = context.newPage();
					
					
					
					page.navigate("https://test.dev.procentive.com/logon.jsp");
					
				} catch (PlaywrightException e) {
					// TODO: handle exception
					throw e;
				}


				break;
				
				


			default:
				break;
			}

		} catch (Exception e) {
			e.printStackTrace();
		}

	}
}

**Describe the bug**

Script execution is passed. But in the console window I am geeting this error:

**Note:  I am using Cucumber BDD framework along with testNG**


node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at PipeTransport.send (C:\Users\prust\AppData\Local\Temp\playwright-java-11190404183220920744\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\prust\AppData\Local\Temp\playwright-java-11190404183220920744\package\lib\cli\driver.js:63:57)
    at DispatcherConnection.sendMessageToClient (C:\Users\prust\AppData\Local\Temp\playwright-java-11190404183220920744\package\lib\server\dispatchers\dispatcher.js:187:10)
    at PageDispatcher._dispatchEvent (C:\Users\prust\AppData\Local\Temp\playwright-java-11190404183220920744\package\lib\server\dispatchers\dispatcher.js:108:22)
    at Page.<anonymous> (C:\Users\prust\AppData\Local\Temp\playwright-java-11190404183220920744\package\lib\server\dispatchers\pageDispatcher.js:94:56)
    at Page.emit (node:events:390:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}
The batch file cannot be found.


Add any other details about the problem here.

**Comment by yury-s** [comment]
"The batch file cannot be found." indicates that something has been deleted under the feet while the tests were running. You code looks legit. Can you by any chance provide reproducible example without cucumber that we could run locally?

**Comment by yury-s** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
