### ISSUE TITLE
Exception in thread "main" com.microsoft.playwright.PlaywrightException : Failed to read message from driver, pipe closed.

### ISSUE THREAD

**Issue by kb33git** [microsoft/playwright-java#952]
I am getting exact same issue, because of organization policies we are not allowed to download any external jars/software hence I added PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 to User environment variable and trying to use installed browser binaries.
This is similar to https://github.com/microsoft/playwright-java/issues/635 which is marked as closed but here I am not using any docker, jenkins etc. its simple maven project with playwright dependency and one line of code "Playwright play = Playwright.create();" stack trace as below

I:\ds\tools\jdk8\1.8.0_321\bin\java.exe ...
Skipping browsers download because "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD eny variable is set
Exception in thread "main" com.microsoft.playwright.PlaywrightException : Failed to read message from driver, pipe closed.
at com.microsoft.playwright.impl.Pipe Transport.poll(Pipe Transport.java:75)
at com.microsoft.playwright.impl.Connection.processone Message (Connection.java:202),
at com.microsoft.playwright.impl.ChannelOwner.rununtil(ChannelOwner.java:101)
at com.microsoft.playwright.impl.Connection.sendMessage(Connection.java:115)
at com.microsoft.playwright.impl.ChannelOwner.sendMessage(ChannelOwner.java:94)
at com.microsoft.playwright.impl.Connections Root.initialize(Connection.java:82)
at com.microsoft.playwright.impl.Connection.initializePlaywright(Connection.java:183)
at com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:45)
at com.microsoft.playwright.Playwright.create(Playwright.java:92)
at com.microsoft.playwright.Playwright.create(Playwright.java:96)
at com.jpmorgan.projectplaywright.PlaywrightTest.main(PlaywrightTest.java:7)
Caused by: java.io.EOFException
at com.microsoft.playwright.impl. ReaderThread.readIntLE(Pipe Transport.java:110)
at com.microsoft.playwright.impl. ReaderThread.readMessage(Pipe Transport.java:139)
at com.microsoft.playwright.impl. ReaderThread.run(Pipe Transport.java:125)
Process finished with exit code 1

**Comment by yury-s** [comment]
Apparently playwright driver doesn't start properly, could be that some malware detection interferes with the workflow. Can you run with `DEBUG=pw:browser` and see if there is something relevant in the logs?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
